
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = (T & DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }>)

interface _GlobalComponents {
      'About': typeof import("../../components/About.vue")['default']
    'Blog': typeof import("../../components/Blog.vue")['default']
    'Contact': typeof import("../../components/Contact.vue")['default']
    'Footer': typeof import("../../components/Footer.vue")['default']
    'Header': typeof import("../../components/Header.vue")['default']
    'Navbar': typeof import("../../components/Navbar.vue")['default']
    'Portfolio': typeof import("../../components/Portfolio.vue")['default']
    'Services': typeof import("../../components/Services.vue")['default']
    'Skills': typeof import("../../components/Skills.vue")['default']
    'Testimonials': typeof import("../../components/Testimonials.vue")['default']
    'DarkAbout': typeof import("../../components/dark/About.vue")['default']
    'DarkFAQSBlog': typeof import("../../components/dark/FAQS/Blog.vue")['default']
    'DarkFAQS': typeof import("../../components/dark/FAQS/FAQS.vue")['default']
    'DarkFAQSHeader': typeof import("../../components/dark/FAQS/Header.vue")['default']
    'DarkFAQSTestimonials': typeof import("../../components/dark/FAQS/Testimonials.vue")['default']
    'DarkAboutBlog': typeof import("../../components/dark/about/Blog.vue")['default']
    'DarkAboutFooter': typeof import("../../components/dark/about/Footer.vue")['default']
    'DarkAboutHeader': typeof import("../../components/dark/about/Header.vue")['default']
    'DarkAboutIntro': typeof import("../../components/dark/about/Intro.vue")['default']
    'DarkAboutIntro2': typeof import("../../components/dark/about/Intro2.vue")['default']
    'DarkAboutMarquee': typeof import("../../components/dark/about/Marquee.vue")['default']
    'DarkAboutTeam': typeof import("../../components/dark/about/Team.vue")['default']
    'DarkAboutTestimonials': typeof import("../../components/dark/about/Testimonials.vue")['default']
    'DarkAbout2About': typeof import("../../components/dark/about2/About.vue")['default']
    'DarkAbout2Brands': typeof import("../../components/dark/about2/Brands.vue")['default']
    'DarkAbout2Header': typeof import("../../components/dark/about2/Header.vue")['default']
    'DarkAbout2Intro': typeof import("../../components/dark/about2/Intro.vue")['default']
    'DarkAbout2Marquee': typeof import("../../components/dark/about2/Marquee.vue")['default']
    'DarkAbout2Numbers': typeof import("../../components/dark/about2/Numbers.vue")['default']
    'DarkAbout2Services': typeof import("../../components/dark/about2/Services.vue")['default']
    'DarkAbout3Blog': typeof import("../../components/dark/about3/Blog.vue")['default']
    'DarkAbout3Brands': typeof import("../../components/dark/about3/Brands.vue")['default']
    'DarkAbout3Header': typeof import("../../components/dark/about3/Header.vue")['default']
    'DarkAbout3Intro': typeof import("../../components/dark/about3/Intro.vue")['default']
    'DarkAbout3Intro2': typeof import("../../components/dark/about3/Intro2.vue")['default']
    'DarkAbout3Marquee': typeof import("../../components/dark/about3/Marquee.vue")['default']
    'DarkAbout3Numbers': typeof import("../../components/dark/about3/Numbers.vue")['default']
    'DarkAbout3Services': typeof import("../../components/dark/about3/Services.vue")['default']
    'DarkAbout3Team': typeof import("../../components/dark/about3/Team.vue")['default']
    'DarkAbout3Testimonials': typeof import("../../components/dark/about3/Testimonials.vue")['default']
    'DarkAsymmetricPortfolioFooter': typeof import("../../components/dark/asymmetric-portfolio/Footer.vue")['default']
    'DarkAsymmetricPortfolioNavbar': typeof import("../../components/dark/asymmetric-portfolio/Navbar.vue")['default']
    'DarkAsymmetricPortfolio': typeof import("../../components/dark/asymmetric-portfolio/Portfolio.vue")['default']
    'DarkBlogClassicBlogs': typeof import("../../components/dark/blog-classic/Blogs.vue")['default']
    'DarkBlogClassicFooter': typeof import("../../components/dark/blog-classic/Footer.vue")['default']
    'DarkBlogClassicHeader': typeof import("../../components/dark/blog-classic/Header.vue")['default']
    'DarkBlogDetailsBlog': typeof import("../../components/dark/blog-details/Blog.vue")['default']
    'DarkBlogDetailsFooter': typeof import("../../components/dark/blog-details/Footer.vue")['default']
    'DarkBlogDetailsRecent': typeof import("../../components/dark/blog-details/Recent.vue")['default']
    'DarkBlogDetailsSlider': typeof import("../../components/dark/blog-details/Slider.vue")['default']
    'DarkBlogListBlogs': typeof import("../../components/dark/blog-list/Blogs.vue")['default']
    'DarkBlogListFooter': typeof import("../../components/dark/blog-list/Footer.vue")['default']
    'DarkBlogListHeader': typeof import("../../components/dark/blog-list/Header.vue")['default']
    'DarkBlogList2Blogs': typeof import("../../components/dark/blog-list2/Blogs.vue")['default']
    'DarkBlogList2Footer': typeof import("../../components/dark/blog-list2/Footer.vue")['default']
    'DarkBlogList2Header': typeof import("../../components/dark/blog-list2/Header.vue")['default']
    'DarkCommonFooter': typeof import("../../components/dark/common/Footer.vue")['default']
    'DarkCommonLines': typeof import("../../components/dark/common/Lines.vue")['default']
    'DarkCommonProgressScroll': typeof import("../../components/dark/common/ProgressScroll.vue")['default']
    'DarkCommonCusor': typeof import("../../components/dark/common/cusor.vue")['default']
    'DarkCommonLoader': typeof import("../../components/dark/common/loader.vue")['default']
    'DarkContact': typeof import("../../components/dark/contact/Contact.vue")['default']
    'DarkContactHeader': typeof import("../../components/dark/contact/Header.vue")['default']
    'DarkContact2Contact': typeof import("../../components/dark/contact2/Contact.vue")['default']
    'DarkContact2Map': typeof import("../../components/dark/contact2/Map.vue")['default']
    'DarkContact3Contact': typeof import("../../components/dark/contact3/Contact.vue")['default']
    'DarkContact3Header': typeof import("../../components/dark/contact3/Header.vue")['default']
    'DarkContact3Map': typeof import("../../components/dark/contact3/Map.vue")['default']
    'DarkCreativeAgencyBlog': typeof import("../../components/dark/creative-agency/Blog.vue")['default']
    'DarkCreativeAgencyBrands': typeof import("../../components/dark/creative-agency/Brands.vue")['default']
    'DarkCreativeAgencyFooter': typeof import("../../components/dark/creative-agency/Footer.vue")['default']
    'DarkCreativeAgencyHeader': typeof import("../../components/dark/creative-agency/Header.vue")['default']
    'DarkCreativeAgencyImageScale': typeof import("../../components/dark/creative-agency/ImageScale.vue")['default']
    'DarkCreativeAgencyMarquee': typeof import("../../components/dark/creative-agency/Marquee.vue")['default']
    'DarkCreativeAgencyNavbar': typeof import("../../components/dark/creative-agency/Navbar.vue")['default']
    'DarkCreativeAgencyNumbers': typeof import("../../components/dark/creative-agency/Numbers.vue")['default']
    'DarkCreativeAgencyPortfolio': typeof import("../../components/dark/creative-agency/Portfolio.vue")['default']
    'DarkCreativeAgencyServices': typeof import("../../components/dark/creative-agency/Services.vue")['default']
    'DarkCreativeAgencySkills': typeof import("../../components/dark/creative-agency/Skills.vue")['default']
    'DarkCreativeAgencyTestimonials': typeof import("../../components/dark/creative-agency/Testimonials.vue")['default']
    'DarkCreativePortfolioAbout': typeof import("../../components/dark/creative-portfolio/About.vue")['default']
    'DarkCreativePortfolioBlog': typeof import("../../components/dark/creative-portfolio/Blog.vue")['default']
    'DarkCreativePortfolioFooter': typeof import("../../components/dark/creative-portfolio/Footer.vue")['default']
    'DarkCreativePortfolioHeader': typeof import("../../components/dark/creative-portfolio/Header.vue")['default']
    'DarkCreativePortfolioMarquee': typeof import("../../components/dark/creative-portfolio/Marquee.vue")['default']
    'DarkCreativePortfolioNavbar': typeof import("../../components/dark/creative-portfolio/Navbar.vue")['default']
    'DarkCreativePortfolio': typeof import("../../components/dark/creative-portfolio/Portfolio.vue")['default']
    'DarkCreativePortfolioServices': typeof import("../../components/dark/creative-portfolio/Services.vue")['default']
    'DarkCreativePortfolioTeam': typeof import("../../components/dark/creative-portfolio/Team.vue")['default']
    'DarkCreativePortfolioTestimonials': typeof import("../../components/dark/creative-portfolio/Testimonials.vue")['default']
    'DarkDigitalAgencyBlog': typeof import("../../components/dark/digital-agency/Blog.vue")['default']
    'DarkDigitalAgencyBrands': typeof import("../../components/dark/digital-agency/Brands.vue")['default']
    'DarkDigitalAgencyFooter': typeof import("../../components/dark/digital-agency/Footer.vue")['default']
    'DarkDigitalAgencyHeader': typeof import("../../components/dark/digital-agency/Header.vue")['default']
    'DarkDigitalAgencyPortfolio': typeof import("../../components/dark/digital-agency/Portfolio.vue")['default']
    'DarkDigitalAgencyPrice': typeof import("../../components/dark/digital-agency/Price.vue")['default']
    'DarkDigitalAgencyProcess': typeof import("../../components/dark/digital-agency/Process.vue")['default']
    'DarkDigitalAgencyServices': typeof import("../../components/dark/digital-agency/Services.vue")['default']
    'DarkDigitalAgencySkills': typeof import("../../components/dark/digital-agency/Skills.vue")['default']
    'DarkDigitalAgencyTeam': typeof import("../../components/dark/digital-agency/Team.vue")['default']
    'DarkDigitalAgencyTestimonials': typeof import("../../components/dark/digital-agency/Testimonials.vue")['default']
    'DarkError404Error': typeof import("../../components/dark/error404/Error.vue")['default']
    'DarkHomeMainBlog': typeof import("../../components/dark/home-main/Blog.vue")['default']
    'DarkHomeMainClients': typeof import("../../components/dark/home-main/Clients.vue")['default']
    'DarkHomeMainFooter': typeof import("../../components/dark/home-main/Footer.vue")['default']
    'DarkHomeMainHeader': typeof import("../../components/dark/home-main/Header.vue")['default']
    'DarkHomeMainIntro': typeof import("../../components/dark/home-main/Intro.vue")['default']
    'DarkHomeMainMarquee': typeof import("../../components/dark/home-main/Marquee.vue")['default']
    'DarkHomeMainPortfolio': typeof import("../../components/dark/home-main/Portfolio.vue")['default']
    'DarkHomeMainServices': typeof import("../../components/dark/home-main/Services.vue")['default']
    'DarkHomeMainServices2': typeof import("../../components/dark/home-main/Services2.vue")['default']
    'DarkHomeMainTeam': typeof import("../../components/dark/home-main/Team.vue")['default']
    'DarkHomeMainTestimonials': typeof import("../../components/dark/home-main/Testimonials.vue")['default']
    'DarkInteractiveFullInteractive': typeof import("../../components/dark/interactive-full/Interactive.vue")['default']
    'DarkInteractiveVerticalInteractive': typeof import("../../components/dark/interactive-vertical/Interactive.vue")['default']
    'DarkLandingPreviewAmazing': typeof import("../../components/dark/landing-preview/Amazing.vue")['default']
    'DarkLandingPreviewFooter': typeof import("../../components/dark/landing-preview/Footer.vue")['default']
    'DarkLandingPreviewGridDemos': typeof import("../../components/dark/landing-preview/GridDemos.vue")['default']
    'DarkLandingPreviewHeader': typeof import("../../components/dark/landing-preview/Header.vue")['default']
    'DarkLandingPreviewInnerPages': typeof import("../../components/dark/landing-preview/InnerPages.vue")['default']
    'DarkLandingPreviewNavTop': typeof import("../../components/dark/landing-preview/NavTop.vue")['default']
    'DarkLandingPreviewPorfolios': typeof import("../../components/dark/landing-preview/Porfolios.vue")['default']
    'DarkLandingPreviewStartSection': typeof import("../../components/dark/landing-preview/StartSection.vue")['default']
    'DarkLandingPreviewTestimonials': typeof import("../../components/dark/landing-preview/Testimonials.vue")['default']
    'DarkLandingPreviewUpdates': typeof import("../../components/dark/landing-preview/Updates.vue")['default']
    'DarkMinimalPortfolioFooter': typeof import("../../components/dark/minimal-portfolio/Footer.vue")['default']
    'DarkMinimalPortfolioTestimonials': typeof import("../../components/dark/minimal-portfolio/Testimonials.vue")['default']
    'DarkMinimalPortfolio': typeof import("../../components/dark/minimal-portfolio/portfolio.vue")['default']
    'DarkModernAgencyAbout': typeof import("../../components/dark/modern-agency/About.vue")['default']
    'DarkModernAgencyBlog': typeof import("../../components/dark/modern-agency/Blog.vue")['default']
    'DarkModernAgencyBrands': typeof import("../../components/dark/modern-agency/Brands.vue")['default']
    'DarkModernAgencyFooter': typeof import("../../components/dark/modern-agency/Footer.vue")['default']
    'DarkModernAgencyHeader': typeof import("../../components/dark/modern-agency/Header.vue")['default']
    'DarkModernAgencyMarquee': typeof import("../../components/dark/modern-agency/Marquee.vue")['default']
    'DarkModernAgencyNumber': typeof import("../../components/dark/modern-agency/Number.vue")['default']
    'DarkModernAgencyPortfolio': typeof import("../../components/dark/modern-agency/Portfolio.vue")['default']
    'DarkModernAgencyServices': typeof import("../../components/dark/modern-agency/Services.vue")['default']
    'DarkModernAgencyServicesTab': typeof import("../../components/dark/modern-agency/ServicesTab.vue")['default']
    'DarkModernAgencyTeam': typeof import("../../components/dark/modern-agency/Team.vue")['default']
    'DarkModernAgencyTestimonials': typeof import("../../components/dark/modern-agency/Testimonials.vue")['default']
    'DarkModernStartupAbout': typeof import("../../components/dark/modern-startup/About.vue")['default']
    'DarkModernStartupBlog': typeof import("../../components/dark/modern-startup/Blog.vue")['default']
    'DarkModernStartupClients': typeof import("../../components/dark/modern-startup/Clients.vue")['default']
    'DarkModernStartupContact': typeof import("../../components/dark/modern-startup/Contact.vue")['default']
    'DarkModernStartupFooter': typeof import("../../components/dark/modern-startup/Footer.vue")['default']
    'DarkModernStartupHeader': typeof import("../../components/dark/modern-startup/Header.vue")['default']
    'DarkModernStartupImageScale': typeof import("../../components/dark/modern-startup/ImageScale.vue")['default']
    'DarkModernStartupMarquee': typeof import("../../components/dark/modern-startup/Marquee.vue")['default']
    'DarkModernStartupNavbar': typeof import("../../components/dark/modern-startup/Navbar.vue")['default']
    'DarkModernStartupPortfolio': typeof import("../../components/dark/modern-startup/Portfolio.vue")['default']
    'DarkModernStartupServices': typeof import("../../components/dark/modern-startup/Services.vue")['default']
    'DarkModernStartupSkills': typeof import("../../components/dark/modern-startup/Skills.vue")['default']
    'DarkModernStartupTestimonials': typeof import("../../components/dark/modern-startup/Testimonials.vue")['default']
    'DarkPersonalVcardContact': typeof import("../../components/dark/personal-vcard/Contact.vue")['default']
    'DarkPersonalVcardFooter': typeof import("../../components/dark/personal-vcard/Footer.vue")['default']
    'DarkPersonalVcardIntro': typeof import("../../components/dark/personal-vcard/Intro.vue")['default']
    'DarkPersonalVcardNavbar': typeof import("../../components/dark/personal-vcard/Navbar.vue")['default']
    'DarkPersonalVcardPortfolio': typeof import("../../components/dark/personal-vcard/Portfolio.vue")['default']
    'DarkPersonalVcardResume': typeof import("../../components/dark/personal-vcard/Resume.vue")['default']
    'DarkPersonalVcardServices': typeof import("../../components/dark/personal-vcard/Services.vue")['default']
    'DarkPersonalVcardSkills': typeof import("../../components/dark/personal-vcard/Skills.vue")['default']
    'DarkPersonalVcardTestimonials': typeof import("../../components/dark/personal-vcard/Testimonials.vue")['default']
    'DarkPersonalVcardPage': typeof import("../../components/dark/personal-vcard/VcardPage.vue")['default']
    'DarkPortfolioCaptionHeader': typeof import("../../components/dark/portfolio-caption/Header.vue")['default']
    'DarkPortfolioCaptionNavbar': typeof import("../../components/dark/portfolio-caption/Navbar.vue")['default']
    'DarkPortfolioCaptionPortfolio': typeof import("../../components/dark/portfolio-caption/Portfolio.vue")['default']
    'DarkPortfolioGalleryHeader': typeof import("../../components/dark/portfolio-gallery/Header.vue")['default']
    'DarkPortfolioGalleryPortfolio': typeof import("../../components/dark/portfolio-gallery/Portfolio.vue")['default']
    'DarkPortfolioMasonryHeader': typeof import("../../components/dark/portfolio-masonry/Header.vue")['default']
    'DarkPortfolioMasonryPortfolio': typeof import("../../components/dark/portfolio-masonry/Portfolio.vue")['default']
    'DarkPortfolioMetroHeader': typeof import("../../components/dark/portfolio-metro/Header.vue")['default']
    'DarkPortfolioMetroPortfolio': typeof import("../../components/dark/portfolio-metro/Portfolio.vue")['default']
    'DarkPortfolioOutlineFooter': typeof import("../../components/dark/portfolio-outline/Footer.vue")['default']
    'DarkPortfolioOutlineHeader': typeof import("../../components/dark/portfolio-outline/Header.vue")['default']
    'DarkPortfolioOutlinePortfolio': typeof import("../../components/dark/portfolio-outline/Portfolio.vue")['default']
    'DarkPortfolioParallaxPortfolio': typeof import("../../components/dark/portfolio-parallax/Portfolio.vue")['default']
    'DarkPortfolioStandardHeader': typeof import("../../components/dark/portfolio-standard/Header.vue")['default']
    'DarkPortfolioStandardPortfolio': typeof import("../../components/dark/portfolio-standard/Portfolio.vue")['default']
    'DarkPortfolioStickyHeader': typeof import("../../components/dark/portfolio-sticky/Header.vue")['default']
    'DarkPortfolioStickyPortfolio': typeof import("../../components/dark/portfolio-sticky/Portfolio.vue")['default']
    'DarkProject1Challenge': typeof import("../../components/dark/project1/Challenge.vue")['default']
    'DarkProject1Header': typeof import("../../components/dark/project1/Header.vue")['default']
    'DarkProject1Next': typeof import("../../components/dark/project1/Next.vue")['default']
    'DarkProject1Solution': typeof import("../../components/dark/project1/Solution.vue")['default']
    'DarkProject1Wroks': typeof import("../../components/dark/project1/Wroks.vue")['default']
    'DarkProject2Challenge': typeof import("../../components/dark/project2/Challenge.vue")['default']
    'DarkProject2Header': typeof import("../../components/dark/project2/Header.vue")['default']
    'DarkProject2Next': typeof import("../../components/dark/project2/Next.vue")['default']
    'DarkProject2Story': typeof import("../../components/dark/project2/Story.vue")['default']
    'DarkProject3Challenge': typeof import("../../components/dark/project3/Challenge.vue")['default']
    'DarkProject3Header': typeof import("../../components/dark/project3/Header.vue")['default']
    'DarkProject3Solution': typeof import("../../components/dark/project3/Solution.vue")['default']
    'DarkProject3Works': typeof import("../../components/dark/project3/Works.vue")['default']
    'DarkProject3Works2': typeof import("../../components/dark/project3/Works2.vue")['default']
    'DarkProject4Challenge': typeof import("../../components/dark/project4/Challenge.vue")['default']
    'DarkProject4Header': typeof import("../../components/dark/project4/Header.vue")['default']
    'DarkProject4Solution': typeof import("../../components/dark/project4/Solution.vue")['default']
    'DarkProject4Works': typeof import("../../components/dark/project4/Works.vue")['default']
    'DarkProject4Works2': typeof import("../../components/dark/project4/Works2.vue")['default']
    'DarkProject5Challenge': typeof import("../../components/dark/project5/Challenge.vue")['default']
    'DarkProject5Header': typeof import("../../components/dark/project5/Header.vue")['default']
    'DarkProject5Solution': typeof import("../../components/dark/project5/Solution.vue")['default']
    'DarkProject5Works': typeof import("../../components/dark/project5/Works.vue")['default']
    'DarkProject5Works2': typeof import("../../components/dark/project5/Works2.vue")['default']
    'DarkProject6Header': typeof import("../../components/dark/project6/Header.vue")['default']
    'DarkProject6Works': typeof import("../../components/dark/project6/Works.vue")['default']
    'DarkServicesDetailsFAQS': typeof import("../../components/dark/services-details/FAQS.vue")['default']
    'DarkServicesDetailsHeader': typeof import("../../components/dark/services-details/Header.vue")['default']
    'DarkServicesDetailsProcess': typeof import("../../components/dark/services-details/Process.vue")['default']
    'DarkServicesDetailsServices': typeof import("../../components/dark/services-details/Services.vue")['default']
    'DarkServicesDetailsServices2': typeof import("../../components/dark/services-details/Services2.vue")['default']
    'DarkServicesBlog': typeof import("../../components/dark/services/Blog.vue")['default']
    'DarkServicesHeader': typeof import("../../components/dark/services/Header.vue")['default']
    'DarkServicesMarquee': typeof import("../../components/dark/services/Marquee.vue")['default']
    'DarkServicesPrice': typeof import("../../components/dark/services/Price.vue")['default']
    'DarkServicesProcess': typeof import("../../components/dark/services/Process.vue")['default']
    'DarkServices': typeof import("../../components/dark/services/Services.vue")['default']
    'DarkServices2Brands': typeof import("../../components/dark/services2/Brands.vue")['default']
    'DarkServices2Header': typeof import("../../components/dark/services2/Header.vue")['default']
    'DarkServices2MainFeat': typeof import../../components/About.vue.vue")['default']
    'DarkServices2Services': typeof import("../../components/dark/services2/Services.vue")['default']
    'DarkShowcaseCarouselHeader': typeof import("../../components/dark/showcase-carousel/Header.vue")['default']
    'DarkShowcaseFullscreenHeader': typeof import("../../components/dark/showcase-fullscreen/Header.vue")['default']
    'DarkShowcaseHalfSliderHeader': typeof import("../../components/dark/showcase-half-slider/Header.vue")['default']
    'DarkShowcaseInteractiveCenterInteractive': typeof import("../../components/dark/showcase-interactive-center/Interactive.vue")['default']
    'DarkTeamSingleSkills': typeof import("../../components/dark/team-single/Skills.vue")['default']
    'DarkTeamSingleTeam': typeof import("../../components/dark/team-single/Team.vue")['default']
    'DarkTeamHeader': typeof import("../../components/dark/team/Header.vue")['default']
    'DarkTeam': typeof import("../../components/dark/team/Team.vue")['default']
    'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
    'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
    'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
      'LazyAbout': LazyComponent<typeof import("../../components/About.vue")['default']>
    'LazyBlog': LazyComponent<typeof import("../../components/Blog.vue")['default']>
    'LazyContact': LazyComponent<typeof import("../../components/Contact.vue")['default']>
    'LazyFooter': LazyComponent<typeof import("../../components/Footer.vue")['default']>
    'LazyHeader': LazyComponent<typeof import("../../components/Header.vue")['default']>
    'LazyNavbar': LazyComponent<typeof import("../../components/Navbar.vue")['default']>
    'LazyPortfolio': LazyComponent<typeof import("../../components/Portfolio.vue")['default']>
    'LazyServices': LazyComponent<typeof import("../../components/Services.vue")['default']>
    'LazySkills': LazyComponent<typeof import("../../components/Skills.vue")['default']>
    'LazyTestimonials': LazyComponent<typeof import("../../components/Testimonials.vue")['default']>
    'LazyDarkAbout': LazyComponent<typeof import("../../components/dark/About.vue")['default']>
    'LazyDarkFAQSBlog': LazyComponent<typeof import("../../components/dark/FAQS/Blog.vue")['default']>
    'LazyDarkFAQS': LazyComponent<typeof import("../../components/dark/FAQS/FAQS.vue")['default']>
    'LazyDarkFAQSHeader': LazyComponent<typeof import("../../components/dark/FAQS/Header.vue")['default']>
    'LazyDarkFAQSTestimonials': LazyComponent<typeof import("../../components/dark/FAQS/Testimonials.vue")['default']>
    'LazyDarkAboutBlog': LazyComponent<typeof import("../../components/dark/about/Blog.vue")['default']>
    'LazyDarkAboutFooter': LazyComponent<typeof import("../../components/dark/about/Footer.vue")['default']>
    'LazyDarkAboutHeader': LazyComponent<typeof import("../../components/dark/about/Header.vue")['default']>
    'LazyDarkAboutIntro': LazyComponent<typeof import("../../components/dark/about/Intro.vue")['default']>
    'LazyDarkAboutIntro2': LazyComponent<typeof import("../../components/dark/about/Intro2.vue")['default']>
    'LazyDarkAboutMarquee': LazyComponent<typeof import("../../components/dark/about/Marquee.vue")['default']>
    'LazyDarkAboutTeam': LazyComponent<typeof import("../../components/dark/about/Team.vue")['default']>
    'LazyDarkAboutTestimonials': LazyComponent<typeof import("../../components/dark/about/Testimonials.vue")['default']>
    'LazyDarkAbout2About': LazyComponent<typeof import("../../components/dark/about2/About.vue")['default']>
    'LazyDarkAbout2Brands': LazyComponent<typeof import("../../components/dark/about2/Brands.vue")['default']>
    'LazyDarkAbout2Header': LazyComponent<typeof import("../../components/dark/about2/Header.vue")['default']>
    'LazyDarkAbout2Intro': LazyComponent<typeof import("../../components/dark/about2/Intro.vue")['default']>
    'LazyDarkAbout2Marquee': LazyComponent<typeof import("../../components/dark/about2/Marquee.vue")['default']>
    'LazyDarkAbout2Numbers': LazyComponent<typeof import("../../components/dark/about2/Numbers.vue")['default']>
    'LazyDarkAbout2Services': LazyComponent<typeof import("../../components/dark/about2/Services.vue")['default']>
    'LazyDarkAbout3Blog': LazyComponent<typeof import("../../components/dark/about3/Blog.vue")['default']>
    'LazyDarkAbout3Brands': LazyComponent<typeof import("../../components/dark/about3/Brands.vue")['default']>
    'LazyDarkAbout3Header': LazyComponent<typeof import("../../components/dark/about3/Header.vue")['default']>
    'LazyDarkAbout3Intro': LazyComponent<typeof import("../../components/dark/about3/Intro.vue")['default']>
    'LazyDarkAbout3Intro2': LazyComponent<typeof import("../../components/dark/about3/Intro2.vue")['default']>
    'LazyDarkAbout3Marquee': LazyComponent<typeof import("../../components/dark/about3/Marquee.vue")['default']>
    'LazyDarkAbout3Numbers': LazyComponent<typeof import("../../components/dark/about3/Numbers.vue")['default']>
    'LazyDarkAbout3Services': LazyComponent<typeof import("../../components/dark/about3/Services.vue")['default']>
    'LazyDarkAbout3Team': LazyComponent<typeof import("../../components/dark/about3/Team.vue")['default']>
    'LazyDarkAbout3Testimonials': LazyComponent<typeof import("../../components/dark/about3/Testimonials.vue")['default']>
    'LazyDarkAsymmetricPortfolioFooter': LazyComponent<typeof import("../../components/dark/asymmetric-portfolio/Footer.vue")['default']>
    'LazyDarkAsymmetricPortfolioNavbar': LazyComponent<typeof import("../../components/dark/asymmetric-portfolio/Navbar.vue")['default']>
    'LazyDarkAsymmetricPortfolio': LazyComponent<typeof import("../../components/dark/asymmetric-portfolio/Portfolio.vue")['default']>
    'LazyDarkBlogClassicBlogs': LazyComponent<typeof import("../../components/dark/blog-classic/Blogs.vue")['default']>
    'LazyDarkBlogClassicFooter': LazyComponent<typeof import("../../components/dark/blog-classic/Footer.vue")['default']>
    'LazyDarkBlogClassicHeader': LazyComponent<typeof import("../../components/dark/blog-classic/Header.vue")['default']>
    'LazyDarkBlogDetailsBlog': LazyComponent<typeof import("../../components/dark/blog-details/Blog.vue")['default']>
    'LazyDarkBlogDetailsFooter': LazyComponent<typeof import("../../components/dark/blog-details/Footer.vue")['default']>
    'LazyDarkBlogDetailsRecent': LazyComponent<typeof import("../../components/dark/blog-details/Recent.vue")['default']>
    'LazyDarkBlogDetailsSlider': LazyComponent<typeof import("../../components/dark/blog-details/Slider.vue")['default']>
    'LazyDarkBlogListBlogs': LazyComponent<typeof import("../../components/dark/blog-list/Blogs.vue")['default']>
    'LazyDarkBlogListFooter': LazyComponent<typeof import("../../components/dark/blog-list/Footer.vue")['default']>
    'LazyDarkBlogListHeader': LazyComponent<typeof import("../../components/dark/blog-list/Header.vue")['default']>
    'LazyDarkBlogList2Blogs': LazyComponent<typeof import("../../components/dark/blog-list2/Blogs.vue")['default']>
    'LazyDarkBlogList2Footer': LazyComponent<typeof import("../../components/dark/blog-list2/Footer.vue")['default']>
    'LazyDarkBlogList2Header': LazyComponent<typeof import("../../components/dark/blog-list2/Header.vue")['default']>
    'LazyDarkCommonFooter': LazyComponent<typeof import("../../components/dark/common/Footer.vue")['default']>
    'LazyDarkCommonLines': LazyComponent<typeof import("../../components/dark/common/Lines.vue")['default']>
    'LazyDarkCommonProgressScroll': LazyComponent<typeof import("../../components/dark/common/ProgressScroll.vue")['default']>
    'LazyDarkCommonCusor': LazyComponent<typeof import("../../components/dark/common/cusor.vue")['default']>
    'LazyDarkCommonLoader': LazyComponent<typeof import("../../components/dark/common/loader.vue")['default']>
    'LazyDarkContact': LazyComponent<typeof import("../../components/dark/contact/Contact.vue")['default']>
    'LazyDarkContactHeader': LazyComponent<typeof import("../../components/dark/contact/Header.vue")['default']>
    'LazyDarkContact2Contact': LazyComponent<typeof import("../../components/dark/contact2/Contact.vue")['default']>
    'LazyDarkContact2Map': LazyComponent<typeof import("../../components/dark/contact2/Map.vue")['default']>
    'LazyDarkContact3Contact': LazyComponent<typeof import("../../components/dark/contact3/Contact.vue")['default']>
    'LazyDarkContact3Header': LazyComponent<typeof import("../../components/dark/contact3/Header.vue")['default']>
    'LazyDarkContact3Map': LazyComponent<typeof import("../../components/dark/contact3/Map.vue")['default']>
    'LazyDarkCreativeAgencyBlog': LazyComponent<typeof import("../../components/dark/creative-agency/Blog.vue")['default']>
    'LazyDarkCreativeAgencyBrands': LazyComponent<typeof import("../../components/dark/creative-agency/Brands.vue")['default']>
    'LazyDarkCreativeAgencyFooter': LazyComponent<typeof import("../../components/dark/creative-agency/Footer.vue")['default']>
    'LazyDarkCreativeAgencyHeader': LazyComponent<typeof import("../../components/dark/creative-agency/Header.vue")['default']>
    'LazyDarkCreativeAgencyImageScale': LazyComponent<typeof import("../../components/dark/creative-agency/ImageScale.vue")['default']>
    'LazyDarkCreativeAgencyMarquee': LazyComponent<typeof import("../../components/dark/creative-agency/Marquee.vue")['default']>
    'LazyDarkCreativeAgencyNavbar': LazyComponent<typeof import("../../components/dark/creative-agency/Navbar.vue")['default']>
    'LazyDarkCreativeAgencyNumbers': LazyComponent<typeof import("../../components/dark/creative-agency/Numbers.vue")['default']>
    'LazyDarkCreativeAgencyPortfolio': LazyComponent<typeof import("../../components/dark/creative-agency/Portfolio.vue")['default']>
    'LazyDarkCreativeAgencyServices': LazyComponent<typeof import("../../components/dark/creative-agency/Services.vue")['default']>
    'LazyDarkCreativeAgencySkills': LazyComponent<typeof import("../../components/dark/creative-agency/Skills.vue")['default']>
    'LazyDarkCreativeAgencyTestimonials': LazyComponent<typeof import("../../components/dark/creative-agency/Testimonials.vue")['default']>
    'LazyDarkCreativePortfolioAbout': LazyComponent<typeof import("../../components/dark/creative-portfolio/About.vue")['default']>
    'LazyDarkCreativePortfolioBlog': LazyComponent<typeof import("../../components/dark/creative-portfolio/Blog.vue")['default']>
    'LazyDarkCreativePortfolioFooter': LazyComponent<typeof import("../../components/dark/creative-portfolio/Footer.vue")['default']>
    'LazyDarkCreativePortfolioHeader': LazyComponent<typeof import("../../components/dark/creative-portfolio/Header.vue")['default']>
    'LazyDarkCreativePortfolioMarquee': LazyComponent<typeof import("../../components/dark/creative-portfolio/Marquee.vue")['default']>
    'LazyDarkCreativePortfolioNavbar': LazyComponent<typeof import("../../components/dark/creative-portfolio/Navbar.vue")['default']>
    'LazyDarkCreativePortfolio': LazyComponent<typeof import("../../components/dark/creative-portfolio/Portfolio.vue")['default']>
    'LazyDarkCreativePortfolioServices': LazyComponent<typeof import("../../components/dark/creative-portfolio/Services.vue")['default']>
    'LazyDarkCreativePortfolioTeam': LazyComponent<typeof import("../../components/dark/creative-portfolio/Team.vue")['default']>
    'LazyDarkCreativePortfolioTestimonials': LazyComponent<typeof import("../../components/dark/creative-portfolio/Testimonials.vue")['default']>
    'LazyDarkDigitalAgencyBlog': LazyComponent<typeof import("../../components/dark/digital-agency/Blog.vue")['default']>
    'LazyDarkDigitalAgencyBrands': LazyComponent<typeof import("../../components/dark/digital-agency/Brands.vue")['default']>
    'LazyDarkDigitalAgencyFooter': LazyComponent<typeof import("../../components/dark/digital-agency/Footer.vue")['default']>
    'LazyDarkDigitalAgencyHeader': LazyComponent<typeof import("../../components/dark/digital-agency/Header.vue")['default']>
    'LazyDarkDigitalAgencyPortfolio': LazyComponent<typeof import("../../components/dark/digital-agency/Portfolio.vue")['default']>
    'LazyDarkDigitalAgencyPrice': LazyComponent<typeof import("../../components/dark/digital-agency/Price.vue")['default']>
    'LazyDarkDigitalAgencyProcess': LazyComponent<typeof import("../../components/dark/digital-agency/Process.vue")['default']>
    'LazyDarkDigitalAgencyServices': LazyComponent<typeof import("../../components/dark/digital-agency/Services.vue")['default']>
    'LazyDarkDigitalAgencySkills': LazyComponent<typeof import("../../components/dark/digital-agency/Skills.vue")['default']>
    'LazyDarkDigitalAgencyTeam': LazyComponent<typeof import("../../components/dark/digital-agency/Team.vue")['default']>
    'LazyDarkDigitalAgencyTestimonials': LazyComponent<typeof import("../../components/dark/digital-agency/Testimonials.vue")['default']>
    'LazyDarkError404Error': LazyComponent<typeof import("../../components/dark/error404/Error.vue")['default']>
    'LazyDarkHomeMainBlog': LazyComponent<typeof import("../../components/dark/home-main/Blog.vue")['default']>
    'LazyDarkHomeMainClients': LazyComponent<typeof import("../../components/dark/home-main/Clients.vue")['default']>
    'LazyDarkHomeMainFooter': LazyComponent<typeof import("../../components/dark/home-main/Footer.vue")['default']>
    'LazyDarkHomeMainHeader': LazyComponent<typeof import("../../components/dark/home-main/Header.vue")['default']>
    'LazyDarkHomeMainIntro': LazyComponent<typeof import("../../components/dark/home-main/Intro.vue")['default']>
    'LazyDarkHomeMainMarquee': LazyComponent<typeof import("../../components/dark/home-main/Marquee.vue")['default']>
    'LazyDarkHomeMainPortfolio': LazyComponent<typeof import("../../components/dark/home-main/Portfolio.vue")['default']>
    'LazyDarkHomeMainServices': LazyComponent<typeof import("../../components/dark/home-main/Services.vue")['default']>
    'LazyDarkHomeMainServices2': LazyComponent<typeof import("../../components/dark/home-main/Services2.vue")['default']>
    'LazyDarkHomeMainTeam': LazyComponent<typeof import("../../components/dark/home-main/Team.vue")['default']>
    'LazyDarkHomeMainTestimonials': LazyComponent<typeof import("../../components/dark/home-main/Testimonials.vue")['default']>
    'LazyDarkInteractiveFullInteractive': LazyComponent<typeof import("../../components/dark/interactive-full/Interactive.vue")['default']>
    'LazyDarkInteractiveVerticalInteractive': LazyComponent<typeof import("../../components/dark/interactive-vertical/Interactive.vue")['default']>
    'LazyDarkLandingPreviewAmazing': LazyComponent<typeof import("../../components/dark/landing-preview/Amazing.vue")['default']>
    'LazyDarkLandingPreviewFooter': LazyComponent<typeof import("../../components/dark/landing-preview/Footer.vue")['default']>
    'LazyDarkLandingPreviewGridDemos': LazyComponent<typeof import("../../components/dark/landing-preview/GridDemos.vue")['default']>
    'LazyDarkLandingPreviewHeader': LazyComponent<typeof import("../../components/dark/landing-preview/Header.vue")['default']>
    'LazyDarkLandingPreviewInnerPages': LazyComponent<typeof import("../../components/dark/landing-preview/InnerPages.vue")['default']>
    'LazyDarkLandingPreviewNavTop': LazyComponent<typeof import("../../components/dark/landing-preview/NavTop.vue")['default']>
    'LazyDarkLandingPreviewPorfolios': LazyComponent<typeof import("../../components/dark/landing-preview/Porfolios.vue")['default']>
    'LazyDarkLandingPreviewStartSection': LazyComponent<typeof import("../../components/dark/landing-preview/StartSection.vue")['default']>
    'LazyDarkLandingPreviewTestimonials': LazyComponent<typeof import("../../components/dark/landing-preview/Testimonials.vue")['default']>
    'LazyDarkLandingPreviewUpdates': LazyComponent<typeof import("../../components/dark/landing-preview/Updates.vue")['default']>
    'LazyDarkMinimalPortfolioFooter': LazyComponent<typeof import("../../components/dark/minimal-portfolio/Footer.vue")['default']>
    'LazyDarkMinimalPortfolioTestimonials': LazyComponent<typeof import("../../components/dark/minimal-portfolio/Testimonials.vue")['default']>
    'LazyDarkMinimalPortfolio': LazyComponent<typeof import("../../components/dark/minimal-portfolio/portfolio.vue")['default']>
    'LazyDarkModernAgencyAbout': LazyComponent<typeof import("../../components/dark/modern-agency/About.vue")['default']>
    'LazyDarkModernAgencyBlog': LazyComponent<typeof import("../../components/dark/modern-agency/Blog.vue")['default']>
    'LazyDarkModernAgencyBrands': LazyComponent<typeof import("../../components/dark/modern-agency/Brands.vue")['default']>
    'LazyDarkModernAgencyFooter': LazyComponent<typeof import("../../components/dark/modern-agency/Footer.vue")['default']>
    'LazyDarkModernAgencyHeader': LazyComponent<typeof import("../../components/dark/modern-agency/Header.vue")['default']>
    'LazyDarkModernAgencyMarquee': LazyComponent<typeof import("../../components/dark/modern-agency/Marquee.vue")['default']>
    'LazyDarkModernAgencyNumber': LazyComponent<typeof import("../../components/dark/modern-agency/Number.vue")['default']>
    'LazyDarkModernAgencyPortfolio': LazyComponent<typeof import("../../components/dark/modern-agency/Portfolio.vue")['default']>
    'LazyDarkModernAgencyServices': LazyComponent<typeof import("../../components/dark/modern-agency/Services.vue")['default']>
    'LazyDarkModernAgencyServicesTab': LazyComponent<typeof import("../../components/dark/modern-agency/ServicesTab.vue")['default']>
    'LazyDarkModernAgencyTeam': LazyComponent<typeof import("../../components/dark/modern-agency/Team.vue")['default']>
    'LazyDarkModernAgencyTestimonials': LazyComponent<typeof import("../../components/dark/modern-agency/Testimonials.vue")['default']>
    'LazyDarkModernStartupAbout': LazyComponent<typeof import("../../components/dark/modern-startup/About.vue")['default']>
    'LazyDarkModernStartupBlog': LazyComponent<typeof import("../../components/dark/modern-startup/Blog.vue")['default']>
    'LazyDarkModernStartupClients': LazyComponent<typeof import("../../components/dark/modern-startup/Clients.vue")['default']>
    'LazyDarkModernStartupContact': LazyComponent<typeof import("../../components/dark/modern-startup/Contact.vue")['default']>
    'LazyDarkModernStartupFooter': LazyComponent<typeof import("../../components/dark/modern-startup/Footer.vue")['default']>
    'LazyDarkModernStartupHeader': LazyComponent<typeof import("../../components/dark/modern-startup/Header.vue")['default']>
    'LazyDarkModernStartupImageScale': LazyComponent<typeof import("../../components/dark/modern-startup/ImageScale.vue")['default']>
    'LazyDarkModernStartupMarquee': LazyComponent<typeof import("../../components/dark/modern-startup/Marquee.vue")['default']>
    'LazyDarkModernStartupNavbar': LazyComponent<typeof import("../../components/dark/modern-startup/Navbar.vue")['default']>
    'LazyDarkModernStartupPortfolio': LazyComponent<typeof import("../../components/dark/modern-startup/Portfolio.vue")['default']>
    'LazyDarkModernStartupServices': LazyComponent<typeof import("../../components/dark/modern-startup/Services.vue")['default']>
    'LazyDarkModernStartupSkills': LazyComponent<typeof import("../../components/dark/modern-startup/Skills.vue")['default']>
    'LazyDarkModernStartupTestimonials': LazyComponent<typeof import("../../components/dark/modern-startup/Testimonials.vue")['default']>
    'LazyDarkPersonalVcardContact': LazyComponent<typeof import("../../components/dark/personal-vcard/Contact.vue")['default']>
    'LazyDarkPersonalVcardFooter': LazyComponent<typeof import("../../components/dark/personal-vcard/Footer.vue")['default']>
    'LazyDarkPersonalVcardIntro': LazyComponent<typeof import("../../components/dark/personal-vcard/Intro.vue")['default']>
    'LazyDarkPersonalVcardNavbar': LazyComponent<typeof import("../../components/dark/personal-vcard/Navbar.vue")['default']>
    'LazyDarkPersonalVcardPortfolio': LazyComponent<typeof import("../../components/dark/personal-vcard/Portfolio.vue")['default']>
    'LazyDarkPersonalVcardResume': LazyComponent<typeof import("../../components/dark/personal-vcard/Resume.vue")['default']>
    'LazyDarkPersonalVcardServices': LazyComponent<typeof import("../../components/dark/personal-vcard/Services.vue")['default']>
    'LazyDarkPersonalVcardSkills': LazyComponent<typeof import("../../components/dark/personal-vcard/Skills.vue")['default']>
    'LazyDarkPersonalVcardTestimonials': LazyComponent<typeof import("../../components/dark/personal-vcard/Testimonials.vue")['default']>
    'LazyDarkPersonalVcardPage': LazyComponent<typeof import("../../components/dark/personal-vcard/VcardPage.vue")['default']>
    'LazyDarkPortfolioCaptionHeader': LazyComponent<typeof import("../../components/dark/portfolio-caption/Header.vue")['default']>
    'LazyDarkPortfolioCaptionNavbar': LazyComponent<typeof import("../../components/dark/portfolio-caption/Navbar.vue")['default']>
    'LazyDarkPortfolioCaptionPortfolio': LazyComponent<typeof import("../../components/dark/portfolio-caption/Portfolio.vue")['default']>
    'LazyDarkPortfolioGalleryHeader': LazyComponent<typeof import("../../components/dark/portfolio-gallery/Header.vue")['default']>
    'LazyDarkPortfolioGalleryPortfolio': LazyComponent<typeof import("../../components/dark/portfolio-gallery/Portfolio.vue")['default']>
    'LazyDarkPortfolioMasonryHeader': LazyComponent<typeof import("../../components/dark/portfolio-masonry/Header.vue")['default']>
    'LazyDarkPortfolioMasonryPortfolio': LazyComponent<typeof import("../../components/dark/portfolio-masonry/Portfolio.vue")['default']>
    'LazyDarkPortfolioMetroHeader': LazyComponent<typeof import("../../components/dark/portfolio-metro/Header.vue")['default']>
    'LazyDarkPortfolioMetroPortfolio': LazyComponent<typeof import("../../components/dark/portfolio-metro/Portfolio.vue")['default']>
    'LazyDarkPortfolioOutlineFooter': LazyComponent<typeof import("../../components/dark/portfolio-outline/Footer.vue")['default']>
    'LazyDarkPortfolioOutlineHeader': LazyComponent<typeof import("../../components/dark/portfolio-outline/Header.vue")['default']>
    'LazyDarkPortfolioOutlinePortfolio': LazyComponent<typeof import("../../components/dark/portfolio-outline/Portfolio.vue")['default']>
    'LazyDarkPortfolioParallaxPortfolio': LazyComponent<typeof import("../../components/dark/portfolio-parallax/Portfolio.vue")['default']>
    'LazyDarkPortfolioStandardHeader': LazyComponent<typeof import("../../components/dark/portfolio-standard/Header.vue")['default']>
    'LazyDarkPortfolioStandardPortfolio': LazyComponent<typeof import("../../components/dark/portfolio-standard/Portfolio.vue")['default']>
    'LazyDarkPortfolioStickyHeader': LazyComponent<typeof import("../../components/dark/portfolio-sticky/Header.vue")['default']>
    'LazyDarkPortfolioStickyPortfolio': LazyComponent<typeof import("../../components/dark/portfolio-sticky/Portfolio.vue")['default']>
    'LazyDarkProject1Challenge': LazyComponent<typeof import("../../components/dark/project1/Challenge.vue")['default']>
    'LazyDarkProject1Header': LazyComponent<typeof import("../../components/dark/project1/Header.vue")['default']>
    'LazyDarkProject1Next': LazyComponent<typeof import("../../components/dark/project1/Next.vue")['default']>
    'LazyDarkProject1Solution': LazyComponent<typeof import("../../components/dark/project1/Solution.vue")['default']>
    'LazyDarkProject1Wroks': LazyComponent<typeof import("../../components/dark/project1/Wroks.vue")['default']>
    'LazyDarkProject2Challenge': LazyComponent<typeof import("../../components/dark/project2/Challenge.vue")['default']>
    'LazyDarkProject2Header': LazyComponent<typeof import("../../components/dark/project2/Header.vue")['default']>
    'LazyDarkProject2Next': LazyComponent<typeof import("../../components/dark/project2/Next.vue")['default']>
    'LazyDarkProject2Story': LazyComponent<typeof import("../../components/dark/project2/Story.vue")['default']>
    'LazyDarkProject3Challenge': LazyComponent<typeof import("../../components/dark/project3/Challenge.vue")['default']>
    'LazyDarkProject3Header': LazyComponent<typeof import("../../components/dark/project3/Header.vue")['default']>
    'LazyDarkProject3Solution': LazyComponent<typeof import("../../components/dark/project3/Solution.vue")['default']>
    'LazyDarkProject3Works': LazyComponent<typeof import("../../components/dark/project3/Works.vue")['default']>
    'LazyDarkProject3Works2': LazyComponent<typeof import("../../components/dark/project3/Works2.vue")['default']>
    'LazyDarkProject4Challenge': LazyComponent<typeof import("../../components/dark/project4/Challenge.vue")['default']>
    'LazyDarkProject4Header': LazyComponent<typeof import("../../components/dark/project4/Header.vue")['default']>
    'LazyDarkProject4Solution': LazyComponent<typeof import("../../components/dark/project4/Solution.vue")['default']>
    'LazyDarkProject4Works': LazyComponent<typeof import("../../components/dark/project4/Works.vue")['default']>
    'LazyDarkProject4Works2': LazyComponent<typeof import("../../components/dark/project4/Works2.vue")['default']>
    'LazyDarkProject5Challenge': LazyComponent<typeof import("../../components/dark/project5/Challenge.vue")['default']>
    'LazyDarkProject5Header': LazyComponent<typeof import("../../components/dark/project5/Header.vue")['default']>
    'LazyDarkProject5Solution': LazyComponent<typeof import("../../components/dark/project5/Solution.vue")['default']>
    'LazyDarkProject5Works': LazyComponent<typeof import("../../components/dark/project5/Works.vue")['default']>
    'LazyDarkProject5Works2': LazyComponent<typeof import("../../components/dark/project5/Works2.vue")['default']>
    'LazyDarkProject6Header': LazyComponent<typeof import("../../components/dark/project6/Header.vue")['default']>
    'LazyDarkProject6Works': LazyComponent<typeof import("../../components/dark/project6/Works.vue")['default']>
    'LazyDarkServicesDetailsFAQS': LazyComponent<typeof import("../../components/dark/services-details/FAQS.vue")['default']>
    'LazyDarkServicesDetailsHeader': LazyComponent<typeof import("../../components/dark/services-details/Header.vue")['default']>
    'LazyDarkServicesDetailsProcess': LazyComponent<typeof import("../../components/dark/services-details/Process.vue")['default']>
    'LazyDarkServicesDetailsServices': LazyComponent<typeof import("../../components/dark/services-details/Services.vue")['default']>
    'LazyDarkServicesDetailsServices2': LazyComponent<typeof import("../../components/dark/services-details/Services2.vue")['default']>
    'LazyDarkServicesBlog': LazyComponent<typeof import("../../components/dark/services/Blog.vue")['default']>
    'LazyDarkServicesHeader': LazyComponent<typeof import("../../components/dark/services/Header.vue")['default']>
    'LazyDarkServicesMarquee': LazyComponent<typeof import("../../components/dark/services/Marquee.vue")['default']>
    'LazyDarkServicesPrice': LazyComponent<typeof import("../../components/dark/services/Price.vue")['default']>
    'LazyDarkServicesProcess': LazyComponent<typeof import("../../components/dark/services/Process.vue")['default']>
    'LazyDarkServices': LazyComponent<typeof import("../../components/dark/services/Services.vue")['default']>
    'LazyDarkServices2Brands': LazyComponent<typeof import("../../components/dark/services2/Brands.vue")['default']>
    'LazyDarkServices2Header': LazyComponent<typeof import("../../components/dark/services2/Header.vue")['default']>
    'LazyDarkServices2MainFeat': LazyComponent<typeof import../../components/About.vue.vue")['default']>
    'LazyDarkServices2Services': LazyComponent<typeof import("../../components/dark/services2/Services.vue")['default']>
    'LazyDarkShowcaseCarouselHeader': LazyComponent<typeof import("../../components/dark/showcase-carousel/Header.vue")['default']>
    'LazyDarkShowcaseFullscreenHeader': LazyComponent<typeof import("../../components/dark/showcase-fullscreen/Header.vue")['default']>
    'LazyDarkShowcaseHalfSliderHeader': LazyComponent<typeof import("../../components/dark/showcase-half-slider/Header.vue")['default']>
    'LazyDarkShowcaseInteractiveCenterInteractive': LazyComponent<typeof import("../../components/dark/showcase-interactive-center/Interactive.vue")['default']>
    'LazyDarkTeamSingleSkills': LazyComponent<typeof import("../../components/dark/team-single/Skills.vue")['default']>
    'LazyDarkTeamSingleTeam': LazyComponent<typeof import("../../components/dark/team-single/Team.vue")['default']>
    'LazyDarkTeamHeader': LazyComponent<typeof import("../../components/dark/team/Header.vue")['default']>
    'LazyDarkTeam': LazyComponent<typeof import("../../components/dark/team/Team.vue")['default']>
    'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
    'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
    'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
    'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
    'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
    'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
    'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
    'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
    'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
    'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
    'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
    'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
    'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
    'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
    'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
    'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
    'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
    'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
    'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
    'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
    'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
    'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
    'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
