
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = (T & DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }>)


export const DarkAbout: typeof import("../components/dark/About.vue")['default']
export const DarkFAQSBlog: typeof import("../components/dark/FAQS/Blog.vue")['default']
export const DarkFAQS: typeof import("../components/dark/FAQS/FAQS.vue")['default']
export const DarkFAQSHeader: typeof import("../components/dark/FAQS/Header.vue")['default']
export const DarkFAQSTestimonials: typeof import("../components/dark/FAQS/Testimonials.vue")['default']
export const DarkAboutBlog: typeof import("../components/dark/about/Blog.vue")['default']
export const DarkAboutFooter: typeof import("../components/dark/about/Footer.vue")['default']
export const DarkAboutHeader: typeof import("../components/dark/about/Header.vue")['default']
export const DarkAboutIntro: typeof import("../components/dark/about/Intro.vue")['default']
export const DarkAboutIntro2: typeof import("../components/dark/about/Intro2.vue")['default']
export const DarkAboutMarquee: typeof import("../components/dark/about/Marquee.vue")['default']
export const DarkAboutTeam: typeof import("../components/dark/about/Team.vue")['default']
export const DarkAboutTestimonials: typeof import("../components/dark/about/Testimonials.vue")['default']
export const DarkAbout2About: typeof import("../components/dark/about2/About.vue")['default']
export const DarkAbout2Brands: typeof import("../components/dark/about2/Brands.vue")['default']
export const DarkAbout2Header: typeof import("../components/dark/about2/Header.vue")['default']
export const DarkAbout2Intro: typeof import("../components/dark/about2/Intro.vue")['default']
export const DarkAbout2Marquee: typeof import("../components/dark/about2/Marquee.vue")['default']
export const DarkAbout2Numbers: typeof import("../components/dark/about2/Numbers.vue")['default']
export const DarkAbout2Services: typeof import("../components/dark/about2/Services.vue")['default']
export const DarkAbout3Blog: typeof import("../components/dark/about3/Blog.vue")['default']
export const DarkAbout3Brands: typeof import("../components/dark/about3/Brands.vue")['default']
export const DarkAbout3Header: typeof import("../components/dark/about3/Header.vue")['default']
export const DarkAbout3Intro: typeof import("../components/dark/about3/Intro.vue")['default']
export const DarkAbout3Intro2: typeof import("../components/dark/about3/Intro2.vue")['default']
export const DarkAbout3Marquee: typeof import("../components/dark/about3/Marquee.vue")['default']
export const DarkAbout3Numbers: typeof import("../components/dark/about3/Numbers.vue")['default']
export const DarkAbout3Services: typeof import("../components/dark/about3/Services.vue")['default']
export const DarkAbout3Team: typeof import("../components/dark/about3/Team.vue")['default']
export const DarkAbout3Testimonials: typeof import("../components/dark/about3/Testimonials.vue")['default']
export const DarkAsymmetricPortfolioFooter: typeof import("../components/dark/asymmetric-portfolio/Footer.vue")['default']
export const DarkAsymmetricPortfolioNavbar: typeof import("../components/dark/asymmetric-portfolio/Navbar.vue")['default']
export const DarkAsymmetricPortfolio: typeof import("../components/dark/asymmetric-portfolio/Portfolio.vue")['default']
export const DarkBlogClassicBlogs: typeof import("../components/dark/blog-classic/Blogs.vue")['default']
export const DarkBlogClassicFooter: typeof import("../components/dark/blog-classic/Footer.vue")['default']
export const DarkBlogClassicHeader: typeof import("../components/dark/blog-classic/Header.vue")['default']
export const DarkBlogDetailsBlog: typeof import("../components/dark/blog-details/Blog.vue")['default']
export const DarkBlogDetailsFooter: typeof import("../components/dark/blog-details/Footer.vue")['default']
export const DarkBlogDetailsRecent: typeof import("../components/dark/blog-details/Recent.vue")['default']
export const DarkBlogDetailsSlider: typeof import("../components/dark/blog-details/Slider.vue")['default']
export const DarkBlogListBlogs: typeof import("../components/dark/blog-list/Blogs.vue")['default']
export const DarkBlogListFooter: typeof import("../components/dark/blog-list/Footer.vue")['default']
export const DarkBlogListHeader: typeof import("../components/dark/blog-list/Header.vue")['default']
export const DarkBlogList2Blogs: typeof import("../components/dark/blog-list2/Blogs.vue")['default']
export const DarkBlogList2Footer: typeof import("../components/dark/blog-list2/Footer.vue")['default']
export const DarkBlogList2Header: typeof import("../components/dark/blog-list2/Header.vue")['default']
export const DarkCommonFooter: typeof import("../components/dark/common/Footer.vue")['default']
export const DarkCommonLines: typeof import("../components/dark/common/Lines.vue")['default']
export const DarkCommonProgressScroll: typeof import("../components/dark/common/ProgressScroll.vue")['default']
export const DarkCommonCusor: typeof import("../components/dark/common/cusor.vue")['default']
export const DarkCommonLoader: typeof import("../components/dark/common/loader.vue")['default']
export const DarkContact: typeof import("../components/dark/contact/Contact.vue")['default']
export const DarkContactHeader: typeof import("../components/dark/contact/Header.vue")['default']
export const DarkContact2Contact: typeof import("../components/dark/contact2/Contact.vue")['default']
export const DarkContact2Map: typeof import("../components/dark/contact2/Map.vue")['default']
export const DarkContact3Contact: typeof import("../components/dark/contact3/Contact.vue")['default']
export const DarkContact3Header: typeof import("../components/dark/contact3/Header.vue")['default']
export const DarkContact3Map: typeof import("../components/dark/contact3/Map.vue")['default']
export const DarkCreativeAgencyBlog: typeof import("../components/dark/creative-agency/Blog.vue")['default']
export const DarkCreativeAgencyBrands: typeof import("../components/dark/creative-agency/Brands.vue")['default']
export const DarkCreativeAgencyFooter: typeof import("../components/dark/creative-agency/Footer.vue")['default']
export const DarkCreativeAgencyHeader: typeof import("../components/dark/creative-agency/Header.vue")['default']
export const DarkCreativeAgencyImageScale: typeof import("../components/dark/creative-agency/ImageScale.vue")['default']
export const DarkCreativeAgencyMarquee: typeof import("../components/dark/creative-agency/Marquee.vue")['default']
export const DarkCreativeAgencyNavbar: typeof import("../components/dark/creative-agency/Navbar.vue")['default']
export const DarkCreativeAgencyNumbers: typeof import("../components/dark/creative-agency/Numbers.vue")['default']
export const DarkCreativeAgencyPortfolio: typeof import("../components/dark/creative-agency/Portfolio.vue")['default']
export const DarkCreativeAgencyServices: typeof import("../components/dark/creative-agency/Services.vue")['default']
export const DarkCreativeAgencySkills: typeof import("../components/dark/creative-agency/Skills.vue")['default']
export const DarkCreativeAgencyTestimonials: typeof import("../components/dark/creative-agency/Testimonials.vue")['default']
export const DarkCreativePortfolioAbout: typeof import("../components/dark/creative-portfolio/About.vue")['default']
export const DarkCreativePortfolioBlog: typeof import("../components/dark/creative-portfolio/Blog.vue")['default']
export const DarkCreativePortfolioFooter: typeof import("../components/dark/creative-portfolio/Footer.vue")['default']
export const DarkCreativePortfolioHeader: typeof import("../components/dark/creative-portfolio/Header.vue")['default']
export const DarkCreativePortfolioMarquee: typeof import("../components/dark/creative-portfolio/Marquee.vue")['default']
export const DarkCreativePortfolioNavbar: typeof import("../components/dark/creative-portfolio/Navbar.vue")['default']
export const DarkCreativePortfolio: typeof import("../components/dark/creative-portfolio/Portfolio.vue")['default']
export const DarkCreativePortfolioServices: typeof import("../components/dark/creative-portfolio/Services.vue")['default']
export const DarkCreativePortfolioTeam: typeof import("../components/dark/creative-portfolio/Team.vue")['default']
export const DarkCreativePortfolioTestimonials: typeof import("../components/dark/creative-portfolio/Testimonials.vue")['default']
export const DarkDigitalAgencyBlog: typeof import("../components/dark/digital-agency/Blog.vue")['default']
export const DarkDigitalAgencyBrands: typeof import("../components/dark/digital-agency/Brands.vue")['default']
export const DarkDigitalAgencyFooter: typeof import("../components/dark/digital-agency/Footer.vue")['default']
export const DarkDigitalAgencyHeader: typeof import("../components/dark/digital-agency/Header.vue")['default']
export const DarkDigitalAgencyPortfolio: typeof import("../components/dark/digital-agency/Portfolio.vue")['default']
export const DarkDigitalAgencyPrice: typeof import("../components/dark/digital-agency/Price.vue")['default']
export const DarkDigitalAgencyProcess: typeof import("../components/dark/digital-agency/Process.vue")['default']
export const DarkDigitalAgencyServices: typeof import("../components/dark/digital-agency/Services.vue")['default']
export const DarkDigitalAgencySkills: typeof import("../components/dark/digital-agency/Skills.vue")['default']
export const DarkDigitalAgencyTeam: typeof import("../components/dark/digital-agency/Team.vue")['default']
export const DarkDigitalAgencyTestimonials: typeof import("../components/dark/digital-agency/Testimonials.vue")['default']
export const DarkError404Error: typeof import("../components/dark/error404/Error.vue")['default']
export const DarkHomeFreelancerAbout: typeof import("../components/dark/home-freelancer/About.vue")['default']
export const DarkHomeFreelancerBlog: typeof import("../components/dark/home-freelancer/Blog.vue")['default']
export const DarkHomeFreelancerContact: typeof import("../components/dark/home-freelancer/Contact.vue")['default']
export const DarkHomeFreelancerFooter: typeof import("../components/dark/home-freelancer/Footer.vue")['default']
export const DarkHomeFreelancerHeader: typeof import("../components/dark/home-freelancer/Header.vue")['default']
export const DarkHomeFreelancerNavbar: typeof import("../components/dark/home-freelancer/Navbar.vue")['default']
export const DarkHomeFreelancerPortfolio: typeof import("../components/dark/home-freelancer/Portfolio.vue")['default']
export const DarkHomeFreelancerServices: typeof import("../components/dark/home-freelancer/Services.vue")['default']
export const DarkHomeFreelancerSkills: typeof import("../components/dark/home-freelancer/Skills.vue")['default']
export const DarkHomeFreelancerTestimonials: typeof import("../components/dark/home-freelancer/Testimonials.vue")['default']
export const DarkHomeMainBlog: typeof import("../components/dark/home-main/Blog.vue")['default']
export const DarkHomeMainClients: typeof import("../components/dark/home-main/Clients.vue")['default']
export const DarkHomeMainFooter: typeof import("../components/dark/home-main/Footer.vue")['default']
export const DarkHomeMainHeader: typeof import("../components/dark/home-main/Header.vue")['default']
export const DarkHomeMainIntro: typeof import("../components/dark/home-main/Intro.vue")['default']
export const DarkHomeMainMarquee: typeof import("../components/dark/home-main/Marquee.vue")['default']
export const DarkHomeMainPortfolio: typeof import("../components/dark/home-main/Portfolio.vue")['default']
export const DarkHomeMainServices: typeof import("../components/dark/home-main/Services.vue")['default']
export const DarkHomeMainServices2: typeof import("../components/dark/home-main/Services2.vue")['default']
export const DarkHomeMainTeam: typeof import("../components/dark/home-main/Team.vue")['default']
export const DarkHomeMainTestimonials: typeof import("../components/dark/home-main/Testimonials.vue")['default']
export const DarkInteractiveFullInteractive: typeof import("../components/dark/interactive-full/Interactive.vue")['default']
export const DarkInteractiveVerticalInteractive: typeof import("../components/dark/interactive-vertical/Interactive.vue")['default']
export const DarkLandingPreviewAmazing: typeof import("../components/dark/landing-preview/Amazing.vue")['default']
export const DarkLandingPreviewFooter: typeof import("../components/dark/landing-preview/Footer.vue")['default']
export const DarkLandingPreviewGridDemos: typeof import("../components/dark/landing-preview/GridDemos.vue")['default']
export const DarkLandingPreviewHeader: typeof import("../components/dark/landing-preview/Header.vue")['default']
export const DarkLandingPreviewInnerPages: typeof import("../components/dark/landing-preview/InnerPages.vue")['default']
export const DarkLandingPreviewNavTop: typeof import("../components/dark/landing-preview/NavTop.vue")['default']
export const DarkLandingPreviewPorfolios: typeof import("../components/dark/landing-preview/Porfolios.vue")['default']
export const DarkLandingPreviewStartSection: typeof import("../components/dark/landing-preview/StartSection.vue")['default']
export const DarkLandingPreviewTestimonials: typeof import("../components/dark/landing-preview/Testimonials.vue")['default']
export const DarkLandingPreviewUpdates: typeof import("../components/dark/landing-preview/Updates.vue")['default']
export const DarkMinimalPortfolioFooter: typeof import("../components/dark/minimal-portfolio/Footer.vue")['default']
export const DarkMinimalPortfolioTestimonials: typeof import("../components/dark/minimal-portfolio/Testimonials.vue")['default']
export const DarkMinimalPortfolio: typeof import("../components/dark/minimal-portfolio/portfolio.vue")['default']
export const DarkModernAgencyAbout: typeof import("../components/dark/modern-agency/About.vue")['default']
export const DarkModernAgencyBlog: typeof import("../components/dark/modern-agency/Blog.vue")['default']
export const DarkModernAgencyBrands: typeof import("../components/dark/modern-agency/Brands.vue")['default']
export const DarkModernAgencyFooter: typeof import("../components/dark/modern-agency/Footer.vue")['default']
export const DarkModernAgencyHeader: typeof import("../components/dark/modern-agency/Header.vue")['default']
export const DarkModernAgencyMarquee: typeof import("../components/dark/modern-agency/Marquee.vue")['default']
export const DarkModernAgencyNumber: typeof import("../components/dark/modern-agency/Number.vue")['default']
export const DarkModernAgencyPortfolio: typeof import("../components/dark/modern-agency/Portfolio.vue")['default']
export const DarkModernAgencyServices: typeof import("../components/dark/modern-agency/Services.vue")['default']
export const DarkModernAgencyServicesTab: typeof import("../components/dark/modern-agency/ServicesTab.vue")['default']
export const DarkModernAgencyTeam: typeof import("../components/dark/modern-agency/Team.vue")['default']
export const DarkModernAgencyTestimonials: typeof import("../components/dark/modern-agency/Testimonials.vue")['default']
export const DarkModernStartupAbout: typeof import("../components/dark/modern-startup/About.vue")['default']
export const DarkModernStartupBlog: typeof import("../components/dark/modern-startup/Blog.vue")['default']
export const DarkModernStartupClients: typeof import("../components/dark/modern-startup/Clients.vue")['default']
export const DarkModernStartupContact: typeof import("../components/dark/modern-startup/Contact.vue")['default']
export const DarkModernStartupFooter: typeof import("../components/dark/modern-startup/Footer.vue")['default']
export const DarkModernStartupHeader: typeof import("../components/dark/modern-startup/Header.vue")['default']
export const DarkModernStartupImageScale: typeof import("../components/dark/modern-startup/ImageScale.vue")['default']
export const DarkModernStartupMarquee: typeof import("../components/dark/modern-startup/Marquee.vue")['default']
export const DarkModernStartupNavbar: typeof import("../components/dark/modern-startup/Navbar.vue")['default']
export const DarkModernStartupPortfolio: typeof import("../components/dark/modern-startup/Portfolio.vue")['default']
export const DarkModernStartupServices: typeof import("../components/dark/modern-startup/Services.vue")['default']
export const DarkModernStartupSkills: typeof import("../components/dark/modern-startup/Skills.vue")['default']
export const DarkModernStartupTestimonials: typeof import("../components/dark/modern-startup/Testimonials.vue")['default']
export const DarkPersonalVcardContact: typeof import("../components/dark/personal-vcard/Contact.vue")['default']
export const DarkPersonalVcardFooter: typeof import("../components/dark/personal-vcard/Footer.vue")['default']
export const DarkPersonalVcardIntro: typeof import("../components/dark/personal-vcard/Intro.vue")['default']
export const DarkPersonalVcardNavbar: typeof import("../components/dark/personal-vcard/Navbar.vue")['default']
export const DarkPersonalVcardPortfolio: typeof import("../components/dark/personal-vcard/Portfolio.vue")['default']
export const DarkPersonalVcardResume: typeof import("../components/dark/personal-vcard/Resume.vue")['default']
export const DarkPersonalVcardServices: typeof import("../components/dark/personal-vcard/Services.vue")['default']
export const DarkPersonalVcardSkills: typeof import("../components/dark/personal-vcard/Skills.vue")['default']
export const DarkPersonalVcardTestimonials: typeof import("../components/dark/personal-vcard/Testimonials.vue")['default']
export const DarkPersonalVcardPage: typeof import("../components/dark/personal-vcard/VcardPage.vue")['default']
export const DarkPortfolioCaptionHeader: typeof import("../components/dark/portfolio-caption/Header.vue")['default']
export const DarkPortfolioCaptionNavbar: typeof import("../components/dark/portfolio-caption/Navbar.vue")['default']
export const DarkPortfolioCaptionPortfolio: typeof import("../components/dark/portfolio-caption/Portfolio.vue")['default']
export const DarkPortfolioGalleryHeader: typeof import("../components/dark/portfolio-gallery/Header.vue")['default']
export const DarkPortfolioGalleryPortfolio: typeof import("../components/dark/portfolio-gallery/Portfolio.vue")['default']
export const DarkPortfolioMasonryHeader: typeof import("../components/dark/portfolio-masonry/Header.vue")['default']
export const DarkPortfolioMasonryPortfolio: typeof import("../components/dark/portfolio-masonry/Portfolio.vue")['default']
export const DarkPortfolioMetroHeader: typeof import("../components/dark/portfolio-metro/Header.vue")['default']
export const DarkPortfolioMetroPortfolio: typeof import("../components/dark/portfolio-metro/Portfolio.vue")['default']
export const DarkPortfolioOutlineFooter: typeof import("../components/dark/portfolio-outline/Footer.vue")['default']
export const DarkPortfolioOutlineHeader: typeof import("../components/dark/portfolio-outline/Header.vue")['default']
export const DarkPortfolioOutlinePortfolio: typeof import("../components/dark/portfolio-outline/Portfolio.vue")['default']
export const DarkPortfolioParallaxPortfolio: typeof import("../components/dark/portfolio-parallax/Portfolio.vue")['default']
export const DarkPortfolioStandardHeader: typeof import("../components/dark/portfolio-standard/Header.vue")['default']
export const DarkPortfolioStandardPortfolio: typeof import("../components/dark/portfolio-standard/Portfolio.vue")['default']
export const DarkPortfolioStickyHeader: typeof import("../components/dark/portfolio-sticky/Header.vue")['default']
export const DarkPortfolioStickyPortfolio: typeof import("../components/dark/portfolio-sticky/Portfolio.vue")['default']
export const DarkProject1Challenge: typeof import("../components/dark/project1/Challenge.vue")['default']
export const DarkProject1Header: typeof import("../components/dark/project1/Header.vue")['default']
export const DarkProject1Next: typeof import("../components/dark/project1/Next.vue")['default']
export const DarkProject1Solution: typeof import("../components/dark/project1/Solution.vue")['default']
export const DarkProject1Wroks: typeof import("../components/dark/project1/Wroks.vue")['default']
export const DarkProject2Challenge: typeof import("../components/dark/project2/Challenge.vue")['default']
export const DarkProject2Header: typeof import("../components/dark/project2/Header.vue")['default']
export const DarkProject2Next: typeof import("../components/dark/project2/Next.vue")['default']
export const DarkProject2Story: typeof import("../components/dark/project2/Story.vue")['default']
export const DarkProject3Challenge: typeof import("../components/dark/project3/Challenge.vue")['default']
export const DarkProject3Header: typeof import("../components/dark/project3/Header.vue")['default']
export const DarkProject3Solution: typeof import("../components/dark/project3/Solution.vue")['default']
export const DarkProject3Works: typeof import("../components/dark/project3/Works.vue")['default']
export const DarkProject3Works2: typeof import("../components/dark/project3/Works2.vue")['default']
export const DarkProject4Challenge: typeof import("../components/dark/project4/Challenge.vue")['default']
export const DarkProject4Header: typeof import("../components/dark/project4/Header.vue")['default']
export const DarkProject4Solution: typeof import("../components/dark/project4/Solution.vue")['default']
export const DarkProject4Works: typeof import("../components/dark/project4/Works.vue")['default']
export const DarkProject4Works2: typeof import("../components/dark/project4/Works2.vue")['default']
export const DarkProject5Challenge: typeof import("../components/dark/project5/Challenge.vue")['default']
export const DarkProject5Header: typeof import("../components/dark/project5/Header.vue")['default']
export const DarkProject5Solution: typeof import("../components/dark/project5/Solution.vue")['default']
export const DarkProject5Works: typeof import("../components/dark/project5/Works.vue")['default']
export const DarkProject5Works2: typeof import("../components/dark/project5/Works2.vue")['default']
export const DarkProject6Header: typeof import("../components/dark/project6/Header.vue")['default']
export const DarkProject6Works: typeof import("../components/dark/project6/Works.vue")['default']
export const DarkServicesDetailsFAQS: typeof import("../components/dark/services-details/FAQS.vue")['default']
export const DarkServicesDetailsHeader: typeof import("../components/dark/services-details/Header.vue")['default']
export const DarkServicesDetailsProcess: typeof import("../components/dark/services-details/Process.vue")['default']
export const DarkServicesDetailsServices: typeof import("../components/dark/services-details/Services.vue")['default']
export const DarkServicesDetailsServices2: typeof import("../components/dark/services-details/Services2.vue")['default']
export const DarkServicesBlog: typeof import("../components/dark/services/Blog.vue")['default']
export const DarkServicesHeader: typeof import("../components/dark/services/Header.vue")['default']
export const DarkServicesMarquee: typeof import("../components/dark/services/Marquee.vue")['default']
export const DarkServicesPrice: typeof import("../components/dark/services/Price.vue")['default']
export const DarkServicesProcess: typeof import("../components/dark/services/Process.vue")['default']
export const DarkServices: typeof import("../components/dark/services/Services.vue")['default']
export const DarkServices2Brands: typeof import("../components/dark/services2/Brands.vue")['default']
export const DarkServices2Header: typeof import("../components/dark/services2/Header.vue")['default']
export const DarkServices2MainFeat: typeof import("../components/dark/services2/MainFeat.vue")['default']
export const DarkServices2Services: typeof import("../components/dark/services2/Services.vue")['default']
export const DarkShowcaseCarouselHeader: typeof import("../components/dark/showcase-carousel/Header.vue")['default']
export const DarkShowcaseFullscreenHeader: typeof import("../components/dark/showcase-fullscreen/Header.vue")['default']
export const DarkShowcaseHalfSliderHeader: typeof import("../components/dark/showcase-half-slider/Header.vue")['default']
export const DarkShowcaseInteractiveCenterInteractive: typeof import("../components/dark/showcase-interactive-center/Interactive.vue")['default']
export const DarkTeamSingleSkills: typeof import("../components/dark/team-single/Skills.vue")['default']
export const DarkTeamSingleTeam: typeof import("../components/dark/team-single/Team.vue")['default']
export const DarkTeamHeader: typeof import("../components/dark/team/Header.vue")['default']
export const DarkTeam: typeof import("../components/dark/team/Team.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyDarkAbout: LazyComponent<typeof import("../components/dark/About.vue")['default']>
export const LazyDarkFAQSBlog: LazyComponent<typeof import("../components/dark/FAQS/Blog.vue")['default']>
export const LazyDarkFAQS: LazyComponent<typeof import("../components/dark/FAQS/FAQS.vue")['default']>
export const LazyDarkFAQSHeader: LazyComponent<typeof import("../components/dark/FAQS/Header.vue")['default']>
export const LazyDarkFAQSTestimonials: LazyComponent<typeof import("../components/dark/FAQS/Testimonials.vue")['default']>
export const LazyDarkAboutBlog: LazyComponent<typeof import("../components/dark/about/Blog.vue")['default']>
export const LazyDarkAboutFooter: LazyComponent<typeof import("../components/dark/about/Footer.vue")['default']>
export const LazyDarkAboutHeader: LazyComponent<typeof import("../components/dark/about/Header.vue")['default']>
export const LazyDarkAboutIntro: LazyComponent<typeof import("../components/dark/about/Intro.vue")['default']>
export const LazyDarkAboutIntro2: LazyComponent<typeof import("../components/dark/about/Intro2.vue")['default']>
export const LazyDarkAboutMarquee: LazyComponent<typeof import("../components/dark/about/Marquee.vue")['default']>
export const LazyDarkAboutTeam: LazyComponent<typeof import("../components/dark/about/Team.vue")['default']>
export const LazyDarkAboutTestimonials: LazyComponent<typeof import("../components/dark/about/Testimonials.vue")['default']>
export const LazyDarkAbout2About: LazyComponent<typeof import("../components/dark/about2/About.vue")['default']>
export const LazyDarkAbout2Brands: LazyComponent<typeof import("../components/dark/about2/Brands.vue")['default']>
export const LazyDarkAbout2Header: LazyComponent<typeof import("../components/dark/about2/Header.vue")['default']>
export const LazyDarkAbout2Intro: LazyComponent<typeof import("../components/dark/about2/Intro.vue")['default']>
export const LazyDarkAbout2Marquee: LazyComponent<typeof import("../components/dark/about2/Marquee.vue")['default']>
export const LazyDarkAbout2Numbers: LazyComponent<typeof import("../components/dark/about2/Numbers.vue")['default']>
export const LazyDarkAbout2Services: LazyComponent<typeof import("../components/dark/about2/Services.vue")['default']>
export const LazyDarkAbout3Blog: LazyComponent<typeof import("../components/dark/about3/Blog.vue")['default']>
export const LazyDarkAbout3Brands: LazyComponent<typeof import("../components/dark/about3/Brands.vue")['default']>
export const LazyDarkAbout3Header: LazyComponent<typeof import("../components/dark/about3/Header.vue")['default']>
export const LazyDarkAbout3Intro: LazyComponent<typeof import("../components/dark/about3/Intro.vue")['default']>
export const LazyDarkAbout3Intro2: LazyComponent<typeof import("../components/dark/about3/Intro2.vue")['default']>
export const LazyDarkAbout3Marquee: LazyComponent<typeof import("../components/dark/about3/Marquee.vue")['default']>
export const LazyDarkAbout3Numbers: LazyComponent<typeof import("../components/dark/about3/Numbers.vue")['default']>
export const LazyDarkAbout3Services: LazyComponent<typeof import("../components/dark/about3/Services.vue")['default']>
export const LazyDarkAbout3Team: LazyComponent<typeof import("../components/dark/about3/Team.vue")['default']>
export const LazyDarkAbout3Testimonials: LazyComponent<typeof import("../components/dark/about3/Testimonials.vue")['default']>
export const LazyDarkAsymmetricPortfolioFooter: LazyComponent<typeof import("../components/dark/asymmetric-portfolio/Footer.vue")['default']>
export const LazyDarkAsymmetricPortfolioNavbar: LazyComponent<typeof import("../components/dark/asymmetric-portfolio/Navbar.vue")['default']>
export const LazyDarkAsymmetricPortfolio: LazyComponent<typeof import("../components/dark/asymmetric-portfolio/Portfolio.vue")['default']>
export const LazyDarkBlogClassicBlogs: LazyComponent<typeof import("../components/dark/blog-classic/Blogs.vue")['default']>
export const LazyDarkBlogClassicFooter: LazyComponent<typeof import("../components/dark/blog-classic/Footer.vue")['default']>
export const LazyDarkBlogClassicHeader: LazyComponent<typeof import("../components/dark/blog-classic/Header.vue")['default']>
export const LazyDarkBlogDetailsBlog: LazyComponent<typeof import("../components/dark/blog-details/Blog.vue")['default']>
export const LazyDarkBlogDetailsFooter: LazyComponent<typeof import("../components/dark/blog-details/Footer.vue")['default']>
export const LazyDarkBlogDetailsRecent: LazyComponent<typeof import("../components/dark/blog-details/Recent.vue")['default']>
export const LazyDarkBlogDetailsSlider: LazyComponent<typeof import("../components/dark/blog-details/Slider.vue")['default']>
export const LazyDarkBlogListBlogs: LazyComponent<typeof import("../components/dark/blog-list/Blogs.vue")['default']>
export const LazyDarkBlogListFooter: LazyComponent<typeof import("../components/dark/blog-list/Footer.vue")['default']>
export const LazyDarkBlogListHeader: LazyComponent<typeof import("../components/dark/blog-list/Header.vue")['default']>
export const LazyDarkBlogList2Blogs: LazyComponent<typeof import("../components/dark/blog-list2/Blogs.vue")['default']>
export const LazyDarkBlogList2Footer: LazyComponent<typeof import("../components/dark/blog-list2/Footer.vue")['default']>
export const LazyDarkBlogList2Header: LazyComponent<typeof import("../components/dark/blog-list2/Header.vue")['default']>
export const LazyDarkCommonFooter: LazyComponent<typeof import("../components/dark/common/Footer.vue")['default']>
export const LazyDarkCommonLines: LazyComponent<typeof import("../components/dark/common/Lines.vue")['default']>
export const LazyDarkCommonProgressScroll: LazyComponent<typeof import("../components/dark/common/ProgressScroll.vue")['default']>
export const LazyDarkCommonCusor: LazyComponent<typeof import("../components/dark/common/cusor.vue")['default']>
export const LazyDarkCommonLoader: LazyComponent<typeof import("../components/dark/common/loader.vue")['default']>
export const LazyDarkContact: LazyComponent<typeof import("../components/dark/contact/Contact.vue")['default']>
export const LazyDarkContactHeader: LazyComponent<typeof import("../components/dark/contact/Header.vue")['default']>
export const LazyDarkContact2Contact: LazyComponent<typeof import("../components/dark/contact2/Contact.vue")['default']>
export const LazyDarkContact2Map: LazyComponent<typeof import("../components/dark/contact2/Map.vue")['default']>
export const LazyDarkContact3Contact: LazyComponent<typeof import("../components/dark/contact3/Contact.vue")['default']>
export const LazyDarkContact3Header: LazyComponent<typeof import("../components/dark/contact3/Header.vue")['default']>
export const LazyDarkContact3Map: LazyComponent<typeof import("../components/dark/contact3/Map.vue")['default']>
export const LazyDarkCreativeAgencyBlog: LazyComponent<typeof import("../components/dark/creative-agency/Blog.vue")['default']>
export const LazyDarkCreativeAgencyBrands: LazyComponent<typeof import("../components/dark/creative-agency/Brands.vue")['default']>
export const LazyDarkCreativeAgencyFooter: LazyComponent<typeof import("../components/dark/creative-agency/Footer.vue")['default']>
export const LazyDarkCreativeAgencyHeader: LazyComponent<typeof import("../components/dark/creative-agency/Header.vue")['default']>
export const LazyDarkCreativeAgencyImageScale: LazyComponent<typeof import("../components/dark/creative-agency/ImageScale.vue")['default']>
export const LazyDarkCreativeAgencyMarquee: LazyComponent<typeof import("../components/dark/creative-agency/Marquee.vue")['default']>
export const LazyDarkCreativeAgencyNavbar: LazyComponent<typeof import("../components/dark/creative-agency/Navbar.vue")['default']>
export const LazyDarkCreativeAgencyNumbers: LazyComponent<typeof import("../components/dark/creative-agency/Numbers.vue")['default']>
export const LazyDarkCreativeAgencyPortfolio: LazyComponent<typeof import("../components/dark/creative-agency/Portfolio.vue")['default']>
export const LazyDarkCreativeAgencyServices: LazyComponent<typeof import("../components/dark/creative-agency/Services.vue")['default']>
export const LazyDarkCreativeAgencySkills: LazyComponent<typeof import("../components/dark/creative-agency/Skills.vue")['default']>
export const LazyDarkCreativeAgencyTestimonials: LazyComponent<typeof import("../components/dark/creative-agency/Testimonials.vue")['default']>
export const LazyDarkCreativePortfolioAbout: LazyComponent<typeof import("../components/dark/creative-portfolio/About.vue")['default']>
export const LazyDarkCreativePortfolioBlog: LazyComponent<typeof import("../components/dark/creative-portfolio/Blog.vue")['default']>
export const LazyDarkCreativePortfolioFooter: LazyComponent<typeof import("../components/dark/creative-portfolio/Footer.vue")['default']>
export const LazyDarkCreativePortfolioHeader: LazyComponent<typeof import("../components/dark/creative-portfolio/Header.vue")['default']>
export const LazyDarkCreativePortfolioMarquee: LazyComponent<typeof import("../components/dark/creative-portfolio/Marquee.vue")['default']>
export const LazyDarkCreativePortfolioNavbar: LazyComponent<typeof import("../components/dark/creative-portfolio/Navbar.vue")['default']>
export const LazyDarkCreativePortfolio: LazyComponent<typeof import("../components/dark/creative-portfolio/Portfolio.vue")['default']>
export const LazyDarkCreativePortfolioServices: LazyComponent<typeof import("../components/dark/creative-portfolio/Services.vue")['default']>
export const LazyDarkCreativePortfolioTeam: LazyComponent<typeof import("../components/dark/creative-portfolio/Team.vue")['default']>
export const LazyDarkCreativePortfolioTestimonials: LazyComponent<typeof import("../components/dark/creative-portfolio/Testimonials.vue")['default']>
export const LazyDarkDigitalAgencyBlog: LazyComponent<typeof import("../components/dark/digital-agency/Blog.vue")['default']>
export const LazyDarkDigitalAgencyBrands: LazyComponent<typeof import("../components/dark/digital-agency/Brands.vue")['default']>
export const LazyDarkDigitalAgencyFooter: LazyComponent<typeof import("../components/dark/digital-agency/Footer.vue")['default']>
export const LazyDarkDigitalAgencyHeader: LazyComponent<typeof import("../components/dark/digital-agency/Header.vue")['default']>
export const LazyDarkDigitalAgencyPortfolio: LazyComponent<typeof import("../components/dark/digital-agency/Portfolio.vue")['default']>
export const LazyDarkDigitalAgencyPrice: LazyComponent<typeof import("../components/dark/digital-agency/Price.vue")['default']>
export const LazyDarkDigitalAgencyProcess: LazyComponent<typeof import("../components/dark/digital-agency/Process.vue")['default']>
export const LazyDarkDigitalAgencyServices: LazyComponent<typeof import("../components/dark/digital-agency/Services.vue")['default']>
export const LazyDarkDigitalAgencySkills: LazyComponent<typeof import("../components/dark/digital-agency/Skills.vue")['default']>
export const LazyDarkDigitalAgencyTeam: LazyComponent<typeof import("../components/dark/digital-agency/Team.vue")['default']>
export const LazyDarkDigitalAgencyTestimonials: LazyComponent<typeof import("../components/dark/digital-agency/Testimonials.vue")['default']>
export const LazyDarkError404Error: LazyComponent<typeof import("../components/dark/error404/Error.vue")['default']>
export const LazyDarkHomeFreelancerAbout: LazyComponent<typeof import("../components/dark/home-freelancer/About.vue")['default']>
export const LazyDarkHomeFreelancerBlog: LazyComponent<typeof import("../components/dark/home-freelancer/Blog.vue")['default']>
export const LazyDarkHomeFreelancerContact: LazyComponent<typeof import("../components/dark/home-freelancer/Contact.vue")['default']>
export const LazyDarkHomeFreelancerFooter: LazyComponent<typeof import("../components/dark/home-freelancer/Footer.vue")['default']>
export const LazyDarkHomeFreelancerHeader: LazyComponent<typeof import("../components/dark/home-freelancer/Header.vue")['default']>
export const LazyDarkHomeFreelancerNavbar: LazyComponent<typeof import("../components/dark/home-freelancer/Navbar.vue")['default']>
export const LazyDarkHomeFreelancerPortfolio: LazyComponent<typeof import("../components/dark/home-freelancer/Portfolio.vue")['default']>
export const LazyDarkHomeFreelancerServices: LazyComponent<typeof import("../components/dark/home-freelancer/Services.vue")['default']>
export const LazyDarkHomeFreelancerSkills: LazyComponent<typeof import("../components/dark/home-freelancer/Skills.vue")['default']>
export const LazyDarkHomeFreelancerTestimonials: LazyComponent<typeof import("../components/dark/home-freelancer/Testimonials.vue")['default']>
export const LazyDarkHomeMainBlog: LazyComponent<typeof import("../components/dark/home-main/Blog.vue")['default']>
export const LazyDarkHomeMainClients: LazyComponent<typeof import("../components/dark/home-main/Clients.vue")['default']>
export const LazyDarkHomeMainFooter: LazyComponent<typeof import("../components/dark/home-main/Footer.vue")['default']>
export const LazyDarkHomeMainHeader: LazyComponent<typeof import("../components/dark/home-main/Header.vue")['default']>
export const LazyDarkHomeMainIntro: LazyComponent<typeof import("../components/dark/home-main/Intro.vue")['default']>
export const LazyDarkHomeMainMarquee: LazyComponent<typeof import("../components/dark/home-main/Marquee.vue")['default']>
export const LazyDarkHomeMainPortfolio: LazyComponent<typeof import("../components/dark/home-main/Portfolio.vue")['default']>
export const LazyDarkHomeMainServices: LazyComponent<typeof import("../components/dark/home-main/Services.vue")['default']>
export const LazyDarkHomeMainServices2: LazyComponent<typeof import("../components/dark/home-main/Services2.vue")['default']>
export const LazyDarkHomeMainTeam: LazyComponent<typeof import("../components/dark/home-main/Team.vue")['default']>
export const LazyDarkHomeMainTestimonials: LazyComponent<typeof import("../components/dark/home-main/Testimonials.vue")['default']>
export const LazyDarkInteractiveFullInteractive: LazyComponent<typeof import("../components/dark/interactive-full/Interactive.vue")['default']>
export const LazyDarkInteractiveVerticalInteractive: LazyComponent<typeof import("../components/dark/interactive-vertical/Interactive.vue")['default']>
export const LazyDarkLandingPreviewAmazing: LazyComponent<typeof import("../components/dark/landing-preview/Amazing.vue")['default']>
export const LazyDarkLandingPreviewFooter: LazyComponent<typeof import("../components/dark/landing-preview/Footer.vue")['default']>
export const LazyDarkLandingPreviewGridDemos: LazyComponent<typeof import("../components/dark/landing-preview/GridDemos.vue")['default']>
export const LazyDarkLandingPreviewHeader: LazyComponent<typeof import("../components/dark/landing-preview/Header.vue")['default']>
export const LazyDarkLandingPreviewInnerPages: LazyComponent<typeof import("../components/dark/landing-preview/InnerPages.vue")['default']>
export const LazyDarkLandingPreviewNavTop: LazyComponent<typeof import("../components/dark/landing-preview/NavTop.vue")['default']>
export const LazyDarkLandingPreviewPorfolios: LazyComponent<typeof import("../components/dark/landing-preview/Porfolios.vue")['default']>
export const LazyDarkLandingPreviewStartSection: LazyComponent<typeof import("../components/dark/landing-preview/StartSection.vue")['default']>
export const LazyDarkLandingPreviewTestimonials: LazyComponent<typeof import("../components/dark/landing-preview/Testimonials.vue")['default']>
export const LazyDarkLandingPreviewUpdates: LazyComponent<typeof import("../components/dark/landing-preview/Updates.vue")['default']>
export const LazyDarkMinimalPortfolioFooter: LazyComponent<typeof import("../components/dark/minimal-portfolio/Footer.vue")['default']>
export const LazyDarkMinimalPortfolioTestimonials: LazyComponent<typeof import("../components/dark/minimal-portfolio/Testimonials.vue")['default']>
export const LazyDarkMinimalPortfolio: LazyComponent<typeof import("../components/dark/minimal-portfolio/portfolio.vue")['default']>
export const LazyDarkModernAgencyAbout: LazyComponent<typeof import("../components/dark/modern-agency/About.vue")['default']>
export const LazyDarkModernAgencyBlog: LazyComponent<typeof import("../components/dark/modern-agency/Blog.vue")['default']>
export const LazyDarkModernAgencyBrands: LazyComponent<typeof import("../components/dark/modern-agency/Brands.vue")['default']>
export const LazyDarkModernAgencyFooter: LazyComponent<typeof import("../components/dark/modern-agency/Footer.vue")['default']>
export const LazyDarkModernAgencyHeader: LazyComponent<typeof import("../components/dark/modern-agency/Header.vue")['default']>
export const LazyDarkModernAgencyMarquee: LazyComponent<typeof import("../components/dark/modern-agency/Marquee.vue")['default']>
export const LazyDarkModernAgencyNumber: LazyComponent<typeof import("../components/dark/modern-agency/Number.vue")['default']>
export const LazyDarkModernAgencyPortfolio: LazyComponent<typeof import("../components/dark/modern-agency/Portfolio.vue")['default']>
export const LazyDarkModernAgencyServices: LazyComponent<typeof import("../components/dark/modern-agency/Services.vue")['default']>
export const LazyDarkModernAgencyServicesTab: LazyComponent<typeof import("../components/dark/modern-agency/ServicesTab.vue")['default']>
export const LazyDarkModernAgencyTeam: LazyComponent<typeof import("../components/dark/modern-agency/Team.vue")['default']>
export const LazyDarkModernAgencyTestimonials: LazyComponent<typeof import("../components/dark/modern-agency/Testimonials.vue")['default']>
export const LazyDarkModernStartupAbout: LazyComponent<typeof import("../components/dark/modern-startup/About.vue")['default']>
export const LazyDarkModernStartupBlog: LazyComponent<typeof import("../components/dark/modern-startup/Blog.vue")['default']>
export const LazyDarkModernStartupClients: LazyComponent<typeof import("../components/dark/modern-startup/Clients.vue")['default']>
export const LazyDarkModernStartupContact: LazyComponent<typeof import("../components/dark/modern-startup/Contact.vue")['default']>
export const LazyDarkModernStartupFooter: LazyComponent<typeof import("../components/dark/modern-startup/Footer.vue")['default']>
export const LazyDarkModernStartupHeader: LazyComponent<typeof import("../components/dark/modern-startup/Header.vue")['default']>
export const LazyDarkModernStartupImageScale: LazyComponent<typeof import("../components/dark/modern-startup/ImageScale.vue")['default']>
export const LazyDarkModernStartupMarquee: LazyComponent<typeof import("../components/dark/modern-startup/Marquee.vue")['default']>
export const LazyDarkModernStartupNavbar: LazyComponent<typeof import("../components/dark/modern-startup/Navbar.vue")['default']>
export const LazyDarkModernStartupPortfolio: LazyComponent<typeof import("../components/dark/modern-startup/Portfolio.vue")['default']>
export const LazyDarkModernStartupServices: LazyComponent<typeof import("../components/dark/modern-startup/Services.vue")['default']>
export const LazyDarkModernStartupSkills: LazyComponent<typeof import("../components/dark/modern-startup/Skills.vue")['default']>
export const LazyDarkModernStartupTestimonials: LazyComponent<typeof import("../components/dark/modern-startup/Testimonials.vue")['default']>
export const LazyDarkPersonalVcardContact: LazyComponent<typeof import("../components/dark/personal-vcard/Contact.vue")['default']>
export const LazyDarkPersonalVcardFooter: LazyComponent<typeof import("../components/dark/personal-vcard/Footer.vue")['default']>
export const LazyDarkPersonalVcardIntro: LazyComponent<typeof import("../components/dark/personal-vcard/Intro.vue")['default']>
export const LazyDarkPersonalVcardNavbar: LazyComponent<typeof import("../components/dark/personal-vcard/Navbar.vue")['default']>
export const LazyDarkPersonalVcardPortfolio: LazyComponent<typeof import("../components/dark/personal-vcard/Portfolio.vue")['default']>
export const LazyDarkPersonalVcardResume: LazyComponent<typeof import("../components/dark/personal-vcard/Resume.vue")['default']>
export const LazyDarkPersonalVcardServices: LazyComponent<typeof import("../components/dark/personal-vcard/Services.vue")['default']>
export const LazyDarkPersonalVcardSkills: LazyComponent<typeof import("../components/dark/personal-vcard/Skills.vue")['default']>
export const LazyDarkPersonalVcardTestimonials: LazyComponent<typeof import("../components/dark/personal-vcard/Testimonials.vue")['default']>
export const LazyDarkPersonalVcardPage: LazyComponent<typeof import("../components/dark/personal-vcard/VcardPage.vue")['default']>
export const LazyDarkPortfolioCaptionHeader: LazyComponent<typeof import("../components/dark/portfolio-caption/Header.vue")['default']>
export const LazyDarkPortfolioCaptionNavbar: LazyComponent<typeof import("../components/dark/portfolio-caption/Navbar.vue")['default']>
export const LazyDarkPortfolioCaptionPortfolio: LazyComponent<typeof import("../components/dark/portfolio-caption/Portfolio.vue")['default']>
export const LazyDarkPortfolioGalleryHeader: LazyComponent<typeof import("../components/dark/portfolio-gallery/Header.vue")['default']>
export const LazyDarkPortfolioGalleryPortfolio: LazyComponent<typeof import("../components/dark/portfolio-gallery/Portfolio.vue")['default']>
export const LazyDarkPortfolioMasonryHeader: LazyComponent<typeof import("../components/dark/portfolio-masonry/Header.vue")['default']>
export const LazyDarkPortfolioMasonryPortfolio: LazyComponent<typeof import("../components/dark/portfolio-masonry/Portfolio.vue")['default']>
export const LazyDarkPortfolioMetroHeader: LazyComponent<typeof import("../components/dark/portfolio-metro/Header.vue")['default']>
export const LazyDarkPortfolioMetroPortfolio: LazyComponent<typeof import("../components/dark/portfolio-metro/Portfolio.vue")['default']>
export const LazyDarkPortfolioOutlineFooter: LazyComponent<typeof import("../components/dark/portfolio-outline/Footer.vue")['default']>
export const LazyDarkPortfolioOutlineHeader: LazyComponent<typeof import("../components/dark/portfolio-outline/Header.vue")['default']>
export const LazyDarkPortfolioOutlinePortfolio: LazyComponent<typeof import("../components/dark/portfolio-outline/Portfolio.vue")['default']>
export const LazyDarkPortfolioParallaxPortfolio: LazyComponent<typeof import("../components/dark/portfolio-parallax/Portfolio.vue")['default']>
export const LazyDarkPortfolioStandardHeader: LazyComponent<typeof import("../components/dark/portfolio-standard/Header.vue")['default']>
export const LazyDarkPortfolioStandardPortfolio: LazyComponent<typeof import("../components/dark/portfolio-standard/Portfolio.vue")['default']>
export const LazyDarkPortfolioStickyHeader: LazyComponent<typeof import("../components/dark/portfolio-sticky/Header.vue")['default']>
export const LazyDarkPortfolioStickyPortfolio: LazyComponent<typeof import("../components/dark/portfolio-sticky/Portfolio.vue")['default']>
export const LazyDarkProject1Challenge: LazyComponent<typeof import("../components/dark/project1/Challenge.vue")['default']>
export const LazyDarkProject1Header: LazyComponent<typeof import("../components/dark/project1/Header.vue")['default']>
export const LazyDarkProject1Next: LazyComponent<typeof import("../components/dark/project1/Next.vue")['default']>
export const LazyDarkProject1Solution: LazyComponent<typeof import("../components/dark/project1/Solution.vue")['default']>
export const LazyDarkProject1Wroks: LazyComponent<typeof import("../components/dark/project1/Wroks.vue")['default']>
export const LazyDarkProject2Challenge: LazyComponent<typeof import("../components/dark/project2/Challenge.vue")['default']>
export const LazyDarkProject2Header: LazyComponent<typeof import("../components/dark/project2/Header.vue")['default']>
export const LazyDarkProject2Next: LazyComponent<typeof import("../components/dark/project2/Next.vue")['default']>
export const LazyDarkProject2Story: LazyComponent<typeof import("../components/dark/project2/Story.vue")['default']>
export const LazyDarkProject3Challenge: LazyComponent<typeof import("../components/dark/project3/Challenge.vue")['default']>
export const LazyDarkProject3Header: LazyComponent<typeof import("../components/dark/project3/Header.vue")['default']>
export const LazyDarkProject3Solution: LazyComponent<typeof import("../components/dark/project3/Solution.vue")['default']>
export const LazyDarkProject3Works: LazyComponent<typeof import("../components/dark/project3/Works.vue")['default']>
export const LazyDarkProject3Works2: LazyComponent<typeof import("../components/dark/project3/Works2.vue")['default']>
export const LazyDarkProject4Challenge: LazyComponent<typeof import("../components/dark/project4/Challenge.vue")['default']>
export const LazyDarkProject4Header: LazyComponent<typeof import("../components/dark/project4/Header.vue")['default']>
export const LazyDarkProject4Solution: LazyComponent<typeof import("../components/dark/project4/Solution.vue")['default']>
export const LazyDarkProject4Works: LazyComponent<typeof import("../components/dark/project4/Works.vue")['default']>
export const LazyDarkProject4Works2: LazyComponent<typeof import("../components/dark/project4/Works2.vue")['default']>
export const LazyDarkProject5Challenge: LazyComponent<typeof import("../components/dark/project5/Challenge.vue")['default']>
export const LazyDarkProject5Header: LazyComponent<typeof import("../components/dark/project5/Header.vue")['default']>
export const LazyDarkProject5Solution: LazyComponent<typeof import("../components/dark/project5/Solution.vue")['default']>
export const LazyDarkProject5Works: LazyComponent<typeof import("../components/dark/project5/Works.vue")['default']>
export const LazyDarkProject5Works2: LazyComponent<typeof import("../components/dark/project5/Works2.vue")['default']>
export const LazyDarkProject6Header: LazyComponent<typeof import("../components/dark/project6/Header.vue")['default']>
export const LazyDarkProject6Works: LazyComponent<typeof import("../components/dark/project6/Works.vue")['default']>
export const LazyDarkServicesDetailsFAQS: LazyComponent<typeof import("../components/dark/services-details/FAQS.vue")['default']>
export const LazyDarkServicesDetailsHeader: LazyComponent<typeof import("../components/dark/services-details/Header.vue")['default']>
export const LazyDarkServicesDetailsProcess: LazyComponent<typeof import("../components/dark/services-details/Process.vue")['default']>
export const LazyDarkServicesDetailsServices: LazyComponent<typeof import("../components/dark/services-details/Services.vue")['default']>
export const LazyDarkServicesDetailsServices2: LazyComponent<typeof import("../components/dark/services-details/Services2.vue")['default']>
export const LazyDarkServicesBlog: LazyComponent<typeof import("../components/dark/services/Blog.vue")['default']>
export const LazyDarkServicesHeader: LazyComponent<typeof import("../components/dark/services/Header.vue")['default']>
export const LazyDarkServicesMarquee: LazyComponent<typeof import("../components/dark/services/Marquee.vue")['default']>
export const LazyDarkServicesPrice: LazyComponent<typeof import("../components/dark/services/Price.vue")['default']>
export const LazyDarkServicesProcess: LazyComponent<typeof import("../components/dark/services/Process.vue")['default']>
export const LazyDarkServices: LazyComponent<typeof import("../components/dark/services/Services.vue")['default']>
export const LazyDarkServices2Brands: LazyComponent<typeof import("../components/dark/services2/Brands.vue")['default']>
export const LazyDarkServices2Header: LazyComponent<typeof import("../components/dark/services2/Header.vue")['default']>
export const LazyDarkServices2MainFeat: LazyComponent<typeof import("../components/dark/services2/MainFeat.vue")['default']>
export const LazyDarkServices2Services: LazyComponent<typeof import("../components/dark/services2/Services.vue")['default']>
export const LazyDarkShowcaseCarouselHeader: LazyComponent<typeof import("../components/dark/showcase-carousel/Header.vue")['default']>
export const LazyDarkShowcaseFullscreenHeader: LazyComponent<typeof import("../components/dark/showcase-fullscreen/Header.vue")['default']>
export const LazyDarkShowcaseHalfSliderHeader: LazyComponent<typeof import("../components/dark/showcase-half-slider/Header.vue")['default']>
export const LazyDarkShowcaseInteractiveCenterInteractive: LazyComponent<typeof import("../components/dark/showcase-interactive-center/Interactive.vue")['default']>
export const LazyDarkTeamSingleSkills: LazyComponent<typeof import("../components/dark/team-single/Skills.vue")['default']>
export const LazyDarkTeamSingleTeam: LazyComponent<typeof import("../components/dark/team-single/Team.vue")['default']>
export const LazyDarkTeamHeader: LazyComponent<typeof import("../components/dark/team/Header.vue")['default']>
export const LazyDarkTeam: LazyComponent<typeof import("../components/dark/team/Team.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
